/*
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.serializer;

import com.google.inject.Inject;
import com.jsantos.metadata.plugin.services.MetaDslGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class MetaDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MetaDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_IdGeneratorSimple_APPLICATIONKeyword_4_or_GUIDKeyword_1_or_IDENTITYKeyword_2_or_NONEKeyword_3;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MetaDslGrammarAccess) access;
		match_IdGeneratorSimple_APPLICATIONKeyword_4_or_GUIDKeyword_1_or_IDENTITYKeyword_2_or_NONEKeyword_3 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getIdGeneratorSimpleAccess().getAPPLICATIONKeyword_4()), new TokenAlias(false, false, grammarAccess.getIdGeneratorSimpleAccess().getGUIDKeyword_1()), new TokenAlias(false, false, grammarAccess.getIdGeneratorSimpleAccess().getIDENTITYKeyword_2()), new TokenAlias(false, false, grammarAccess.getIdGeneratorSimpleAccess().getNONEKeyword_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_IdGeneratorSimple_APPLICATIONKeyword_4_or_GUIDKeyword_1_or_IDENTITYKeyword_2_or_NONEKeyword_3.equals(syntax))
				emit_IdGeneratorSimple_APPLICATIONKeyword_4_or_GUIDKeyword_1_or_IDENTITYKeyword_2_or_NONEKeyword_3(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'GUID' | 'IDENTITY' | 'NONE' | 'APPLICATION'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_IdGeneratorSimple_APPLICATIONKeyword_4_or_GUIDKeyword_1_or_IDENTITYKeyword_2_or_NONEKeyword_3(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
