/*
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.serializer;

import com.google.inject.Inject;
import com.jsantos.metadata.plugin.metaDsl.Attribute;
import com.jsantos.metadata.plugin.metaDsl.ColumnStereotype;
import com.jsantos.metadata.plugin.metaDsl.Configuration;
import com.jsantos.metadata.plugin.metaDsl.Constant;
import com.jsantos.metadata.plugin.metaDsl.DataType;
import com.jsantos.metadata.plugin.metaDsl.DataTypeDetails;
import com.jsantos.metadata.plugin.metaDsl.DocumentationBlock;
import com.jsantos.metadata.plugin.metaDsl.DocumentationSection;
import com.jsantos.metadata.plugin.metaDsl.Entity;
import com.jsantos.metadata.plugin.metaDsl.EnuMetadata;
import com.jsantos.metadata.plugin.metaDsl.EnuMetadataRow;
import com.jsantos.metadata.plugin.metaDsl.EnumerationLabel;
import com.jsantos.metadata.plugin.metaDsl.EnumerationLabels;
import com.jsantos.metadata.plugin.metaDsl.GeneralLabelSection;
import com.jsantos.metadata.plugin.metaDsl.IdGenerator;
import com.jsantos.metadata.plugin.metaDsl.IdGeneratorSequence;
import com.jsantos.metadata.plugin.metaDsl.IdGeneratorSimple;
import com.jsantos.metadata.plugin.metaDsl.KeyLabel;
import com.jsantos.metadata.plugin.metaDsl.Label;
import com.jsantos.metadata.plugin.metaDsl.LabelBlock;
import com.jsantos.metadata.plugin.metaDsl.LabelSection;
import com.jsantos.metadata.plugin.metaDsl.Language;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.Metadata;
import com.jsantos.metadata.plugin.metaDsl.MetadataRow;
import com.jsantos.metadata.plugin.metaDsl.MetadataRowCell;
import com.jsantos.metadata.plugin.metaDsl.Model;
import com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock;
import com.jsantos.metadata.plugin.metaDsl.Pattern;
import com.jsantos.metadata.plugin.metaDsl.QuerySourceBlock;
import com.jsantos.metadata.plugin.metaDsl.SQLDECLARATIONSBLOCK;
import com.jsantos.metadata.plugin.metaDsl.SQLFunction;
import com.jsantos.metadata.plugin.metaDsl.Sequence;
import com.jsantos.metadata.plugin.metaDsl.ShortCode;
import com.jsantos.metadata.plugin.metaDsl.SqlFileDependency;
import com.jsantos.metadata.plugin.metaDsl.SqlNative;
import com.jsantos.metadata.plugin.metaDsl.SqlNativeBlock;
import com.jsantos.metadata.plugin.metaDsl.SubTypeDataType;
import com.jsantos.metadata.plugin.metaDsl.TableStereotype;
import com.jsantos.metadata.plugin.services.MetaDslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class MetaDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MetaDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MetaDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MetaDslPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case MetaDslPackage.COLUMN_STEREOTYPE:
				sequence_ColumnStereotype(context, (ColumnStereotype) semanticObject); 
				return; 
			case MetaDslPackage.CONFIGURATION:
				sequence_Configuration(context, (Configuration) semanticObject); 
				return; 
			case MetaDslPackage.CONSTANT:
				sequence_Constant(context, (Constant) semanticObject); 
				return; 
			case MetaDslPackage.DATA_TYPE:
				sequence_DataType(context, (DataType) semanticObject); 
				return; 
			case MetaDslPackage.DATA_TYPE_DETAILS:
				sequence_DataTypeDetails(context, (DataTypeDetails) semanticObject); 
				return; 
			case MetaDslPackage.DOCUMENTATION_BLOCK:
				sequence_DocumentationBlock(context, (DocumentationBlock) semanticObject); 
				return; 
			case MetaDslPackage.DOCUMENTATION_SECTION:
				sequence_DocumentationSection(context, (DocumentationSection) semanticObject); 
				return; 
			case MetaDslPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case MetaDslPackage.ENU_METADATA:
				sequence_EnuMetadata(context, (EnuMetadata) semanticObject); 
				return; 
			case MetaDslPackage.ENU_METADATA_ROW:
				sequence_EnuMetadataRow(context, (EnuMetadataRow) semanticObject); 
				return; 
			case MetaDslPackage.ENUMERATION_LABEL:
				sequence_EnumerationLabel(context, (EnumerationLabel) semanticObject); 
				return; 
			case MetaDslPackage.ENUMERATION_LABELS:
				sequence_EnumerationLabels(context, (EnumerationLabels) semanticObject); 
				return; 
			case MetaDslPackage.GENERAL_LABEL_SECTION:
				sequence_GeneralLabelSection(context, (GeneralLabelSection) semanticObject); 
				return; 
			case MetaDslPackage.ID_GENERATOR:
				sequence_IdGenerator(context, (IdGenerator) semanticObject); 
				return; 
			case MetaDslPackage.ID_GENERATOR_SEQUENCE:
				sequence_IdGeneratorSequence(context, (IdGeneratorSequence) semanticObject); 
				return; 
			case MetaDslPackage.ID_GENERATOR_SIMPLE:
				sequence_IdGeneratorSimple(context, (IdGeneratorSimple) semanticObject); 
				return; 
			case MetaDslPackage.KEY_LABEL:
				sequence_KeyLabel(context, (KeyLabel) semanticObject); 
				return; 
			case MetaDslPackage.LABEL:
				sequence_Label(context, (Label) semanticObject); 
				return; 
			case MetaDslPackage.LABEL_BLOCK:
				sequence_LabelBlock(context, (LabelBlock) semanticObject); 
				return; 
			case MetaDslPackage.LABEL_SECTION:
				sequence_LabelSection(context, (LabelSection) semanticObject); 
				return; 
			case MetaDslPackage.LANGUAGE:
				sequence_Language(context, (Language) semanticObject); 
				return; 
			case MetaDslPackage.METADATA:
				sequence_Metadata(context, (Metadata) semanticObject); 
				return; 
			case MetaDslPackage.METADATA_ROW:
				sequence_MetadataRow(context, (MetadataRow) semanticObject); 
				return; 
			case MetaDslPackage.METADATA_ROW_CELL:
				sequence_MetadataRowCell(context, (MetadataRowCell) semanticObject); 
				return; 
			case MetaDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case MetaDslPackage.OVERRIDE_LABEL_BLOCK:
				sequence_OverrideLabelBlock(context, (OverrideLabelBlock) semanticObject); 
				return; 
			case MetaDslPackage.PATTERN:
				sequence_Pattern(context, (Pattern) semanticObject); 
				return; 
			case MetaDslPackage.QUERY_SOURCE_BLOCK:
				sequence_QuerySourceBlock(context, (QuerySourceBlock) semanticObject); 
				return; 
			case MetaDslPackage.SQLDECLARATIONSBLOCK:
				sequence_SQLDECLARATIONSBLOCK(context, (SQLDECLARATIONSBLOCK) semanticObject); 
				return; 
			case MetaDslPackage.SQL_FUNCTION:
				sequence_SQLFunction(context, (SQLFunction) semanticObject); 
				return; 
			case MetaDslPackage.SEQUENCE:
				sequence_Sequence(context, (Sequence) semanticObject); 
				return; 
			case MetaDslPackage.SHORT_CODE:
				sequence_ShortCode(context, (ShortCode) semanticObject); 
				return; 
			case MetaDslPackage.SQL_FILE_DEPENDENCY:
				sequence_SqlFileDependency(context, (SqlFileDependency) semanticObject); 
				return; 
			case MetaDslPackage.SQL_NATIVE:
				sequence_SqlNative(context, (SqlNative) semanticObject); 
				return; 
			case MetaDslPackage.SQL_NATIVE_BLOCK:
				sequence_SqlNativeBlock(context, (SqlNativeBlock) semanticObject); 
				return; 
			case MetaDslPackage.SUB_TYPE_DATA_TYPE:
				sequence_SubTypeDataType(context, (SubTypeDataType) semanticObject); 
				return; 
			case MetaDslPackage.TABLE_STEREOTYPE:
				sequence_TableStereotype(context, (TableStereotype) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (
	 *         unique?='UQ'? 
	 *         pk?='PK'? 
	 *         name=ID 
	 *         type=[DataType|ID] 
	 *         ((length=NATURAL | maxlength?='MAX') scale=NATURAL?)? 
	 *         notNullable?='NOTNULL'? 
	 *         sameAsAttribute=[Attribute|FQN]? 
	 *         fkto=[Entity|FQN]? 
	 *         multiRefTo=[Entity|FQN]? 
	 *         (default=STRING | defaultConstant=[Constant|ID])? 
	 *         transient?='TRANSIENT'? 
	 *         (stereotypes+=[ColumnStereotype|ID] stereotypes+=[ColumnStereotype|ID]?)? 
	 *         idGenerator=IdGenerator?
	 *     )
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ColumnStereotype returns ColumnStereotype
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_ColumnStereotype(ISerializationContext context, ColumnStereotype semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.COLUMN_STEREOTYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.COLUMN_STEREOTYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColumnStereotypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Configuration returns Configuration
	 *
	 * Constraint:
	 *     (
	 *         languages+=Language+ 
	 *         dataTypes+=DataType+ 
	 *         constants+=Constant* 
	 *         tableStereotypes+=TableStereotype* 
	 *         columnStereotypes+=ColumnStereotype* 
	 *         patterns+=Pattern* 
	 *         (defaultPkGenerationStrategy='NONE' | defaultPkGenerationStrategy='SEQUENCE' | defaultPkGenerationStrategy='IDENTITY') 
	 *         mtClassName=ID?
	 *     )
	 */
	protected void sequence_Configuration(ISerializationContext context, Configuration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Constant returns Constant
	 *
	 * Constraint:
	 *     (name=ID value=STRING)
	 */
	protected void sequence_Constant(ISerializationContext context, Constant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.CONSTANT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.CONSTANT__NAME));
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.CONSTANT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.CONSTANT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getConstantAccess().getValueSTRINGTerminalRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DataTypeDefinition returns DataTypeDetails
	 *     DataTypeDetails returns DataTypeDetails
	 *
	 * Constraint:
	 *     (dbNativeType=ID (withPrecissionAndScale?='WITHPRECISSIONANDSCALE' | withLength?='WITHLENGTH')? javaType=FQN)
	 */
	protected void sequence_DataTypeDetails(ISerializationContext context, DataTypeDetails semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataType returns DataType
	 *
	 * Constraint:
	 *     (name=ID details=DataTypeDefinition)
	 */
	protected void sequence_DataType(ISerializationContext context, DataType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.DATA_TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.DATA_TYPE__NAME));
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.DATA_TYPE__DETAILS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.DATA_TYPE__DETAILS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDataTypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDataTypeAccess().getDetailsDataTypeDefinitionParserRuleCall_2_0(), semanticObject.getDetails());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DocumentationBlock returns DocumentationBlock
	 *
	 * Constraint:
	 *     (attribute=[Attribute|ID]? (documentationText=ML_STRING | documentationText=STRING))
	 */
	protected void sequence_DocumentationBlock(ISerializationContext context, DocumentationBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DocumentationSection returns DocumentationSection
	 *
	 * Constraint:
	 *     (name='DOCUMENTATION' documentationBlocks+=DocumentationBlock+)
	 */
	protected void sequence_DocumentationSection(ISerializationContext context, DocumentationSection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Entity returns Entity
	 *
	 * Constraint:
	 *     (
	 *         fromSQLFile=STRING? 
	 *         sqlFileDependencies+=SqlFileDependency* 
	 *         (entityType='TABLE' | entityType='VIEW' | entityType='SQLQUERY')? 
	 *         name=FQN 
	 *         extends=[Entity|FQN]? 
	 *         (patterns+=[Pattern|ID] patterns+=[Pattern|ID]?)? 
	 *         (stereotypes+=[TableStereotype|ID] stereotypes+=[TableStereotype|ID]?)? 
	 *         attributes+=Attribute* 
	 *         metadata=Metadata? 
	 *         enuMetadata=EnuMetadata? 
	 *         labelSection=LabelSection? 
	 *         enumerationLabels=EnumerationLabels? 
	 *         documentationSection=DocumentationSection? 
	 *         querySourceBlock=QuerySourceBlock?
	 *     )
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EnuMetadataRow returns EnuMetadataRow
	 *
	 * Constraint:
	 *     (key=NATURAL name=ID description=STRING rowValues+=MetadataRowCell*)
	 */
	protected void sequence_EnuMetadataRow(ISerializationContext context, EnuMetadataRow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EnuMetadata returns EnuMetadata
	 *
	 * Constraint:
	 *     enuMetadataRows+=EnuMetadataRow+
	 */
	protected void sequence_EnuMetadata(ISerializationContext context, EnuMetadata semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EnumerationLabel returns EnumerationLabel
	 *
	 * Constraint:
	 *     (enuMetadataRow=[EnuMetadataRow|FQN] (type='SHORTLABEL' | type='LONGLABEL')? labels+=Label*)
	 */
	protected void sequence_EnumerationLabel(ISerializationContext context, EnumerationLabel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EnumerationLabels returns EnumerationLabels
	 *
	 * Constraint:
	 *     enumerationLabel+=EnumerationLabel+
	 */
	protected void sequence_EnumerationLabels(ISerializationContext context, EnumerationLabels semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GeneralLabelSection returns GeneralLabelSection
	 *
	 * Constraint:
	 *     (name='LABELS' keyLabel+=KeyLabel* overrideLabelBlock+=OverrideLabelBlock*)
	 */
	protected void sequence_GeneralLabelSection(ISerializationContext context, GeneralLabelSection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     IdGeneratorTypeBlock returns IdGeneratorSequence
	 *     IdGeneratorSequence returns IdGeneratorSequence
	 *
	 * Constraint:
	 *     (type='SEQUENCE' sequence=[Sequence|FQN])
	 */
	protected void sequence_IdGeneratorSequence(ISerializationContext context, IdGeneratorSequence semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.ID_GENERATOR_TYPE_BLOCK__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.ID_GENERATOR_TYPE_BLOCK__TYPE));
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.ID_GENERATOR_SEQUENCE__SEQUENCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.ID_GENERATOR_SEQUENCE__SEQUENCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIdGeneratorSequenceAccess().getTypeSEQUENCEKeyword_1_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getIdGeneratorSequenceAccess().getSequenceSequenceFQNParserRuleCall_2_0_1(), semanticObject.eGet(MetaDslPackage.Literals.ID_GENERATOR_SEQUENCE__SEQUENCE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     IdGeneratorTypeBlock returns IdGeneratorSimple
	 *     IdGeneratorSimple returns IdGeneratorSimple
	 *
	 * Constraint:
	 *     type='BYRULE'
	 */
	protected void sequence_IdGeneratorSimple(ISerializationContext context, IdGeneratorSimple semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.ID_GENERATOR_TYPE_BLOCK__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.ID_GENERATOR_TYPE_BLOCK__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIdGeneratorSimpleAccess().getTypeBYRULEKeyword_0_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     IdGenerator returns IdGenerator
	 *
	 * Constraint:
	 *     (attribute=[Attribute|ID] typeBlock=IdGeneratorTypeBlock)
	 */
	protected void sequence_IdGenerator(ISerializationContext context, IdGenerator semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.ID_GENERATOR__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.ID_GENERATOR__ATTRIBUTE));
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.ID_GENERATOR__TYPE_BLOCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.ID_GENERATOR__TYPE_BLOCK));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIdGeneratorAccess().getAttributeAttributeIDTerminalRuleCall_1_0_1(), semanticObject.eGet(MetaDslPackage.Literals.ID_GENERATOR__ATTRIBUTE, false));
		feeder.accept(grammarAccess.getIdGeneratorAccess().getTypeBlockIdGeneratorTypeBlockParserRuleCall_2_0(), semanticObject.getTypeBlock());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     KeyLabel returns KeyLabel
	 *
	 * Constraint:
	 *     (key=FQN labels+=Label*)
	 */
	protected void sequence_KeyLabel(ISerializationContext context, KeyLabel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LabelBlock returns LabelBlock
	 *
	 * Constraint:
	 *     ((entity?='ENTITY' | attribute=[Attribute|FQN]) (type='SHORTLABEL' | type='LONGLABEL')? labels+=Label*)
	 */
	protected void sequence_LabelBlock(ISerializationContext context, LabelBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LabelSection returns LabelSection
	 *
	 * Constraint:
	 *     (name='LABELS' labels+=LabelBlock+)
	 */
	protected void sequence_LabelSection(ISerializationContext context, LabelSection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Label returns Label
	 *
	 * Constraint:
	 *     (lang=[Language|ID]? labelText=STRING)
	 */
	protected void sequence_Label(ISerializationContext context, Label semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Language returns Language
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Language(ISerializationContext context, Language semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.LANGUAGE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.LANGUAGE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLanguageAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     MetadataRowCell returns MetadataRowCell
	 *
	 * Constraint:
	 *     (
	 *         stringValue=STRING | 
	 *         stringValue=DOUBLE | 
	 *         stringValue=NATURAL | 
	 *         stringValue=NEGATIVEINT | 
	 *         shortCode=ShortCode | 
	 *         isNull?='NULL' | 
	 *         isDefault?='DEFAULT'
	 *     )
	 */
	protected void sequence_MetadataRowCell(ISerializationContext context, MetadataRowCell semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MetadataRow returns MetadataRow
	 *
	 * Constraint:
	 *     (rowValues+=MetadataRowCell rowValues+=MetadataRowCell*)
	 */
	protected void sequence_MetadataRow(ISerializationContext context, MetadataRow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Metadata returns Metadata
	 *
	 * Constraint:
	 *     (name='METADATA' entity=[Entity|FQN]? metadataRows+=MetadataRow*)
	 */
	protected void sequence_Metadata(ISerializationContext context, Metadata semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (
	 *         (entities+=Entity* ((generalLabelSection=GeneralLabelSection metadatas+=Metadata+) | metadatas+=Metadata+)) | 
	 *         (entities+=Entity* sequences+=Sequence+ ((generalLabelSection=GeneralLabelSection metadatas+=Metadata+) | metadatas+=Metadata+)) | 
	 *         (
	 *             (
	 *                 (entities+=Entity* configuration=Configuration) | 
	 *                 (entities+=Entity* sequences+=Sequence+ configuration=Configuration) | 
	 *                 configuration=Configuration
	 *             ) 
	 *             ((generalLabelSection=GeneralLabelSection metadatas+=Metadata+) | metadatas+=Metadata+)
	 *         ) | 
	 *         (
	 *             (
	 *                 (entities+=Entity* ((configuration=Configuration generalLabelSection=GeneralLabelSection) | generalLabelSection=GeneralLabelSection)) | 
	 *                 (
	 *                     entities+=Entity* 
	 *                     sequences+=Sequence+ 
	 *                     ((configuration=Configuration generalLabelSection=GeneralLabelSection) | generalLabelSection=GeneralLabelSection)
	 *                 ) | 
	 *                 (configuration=Configuration generalLabelSection=GeneralLabelSection) | 
	 *                 generalLabelSection=GeneralLabelSection
	 *             )? 
	 *             sqlNatives+=SqlNative+ 
	 *             metadatas+=Metadata+
	 *         ) | 
	 *         (generalLabelSection=GeneralLabelSection metadatas+=Metadata+) | 
	 *         metadatas+=Metadata+
	 *     )?
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OverrideLabelBlock returns OverrideLabelBlock
	 *
	 * Constraint:
	 *     ((attribute=[Attribute|FQN] | entity=[Entity|FQN] | enuMetadataRow=[EnuMetadataRow|FQN]) (type='SHORTLABEL' | type='LONGLABEL')? labels+=Label*)
	 */
	protected void sequence_OverrideLabelBlock(ISerializationContext context, OverrideLabelBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Pattern returns Pattern
	 *
	 * Constraint:
	 *     (name=ID attributes+=Attribute*)
	 */
	protected void sequence_Pattern(ISerializationContext context, Pattern semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     QuerySourceBlock returns QuerySourceBlock
	 *
	 * Constraint:
	 *     querySource=ML_STRING
	 */
	protected void sequence_QuerySourceBlock(ISerializationContext context, QuerySourceBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.QUERY_SOURCE_BLOCK__QUERY_SOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.QUERY_SOURCE_BLOCK__QUERY_SOURCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getQuerySourceBlockAccess().getQuerySourceML_STRINGTerminalRuleCall_1_0(), semanticObject.getQuerySource());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SQLDECLARATIONSBLOCK returns SQLDECLARATIONSBLOCK
	 *
	 * Constraint:
	 *     sqlFunctions+=SQLFunction+
	 */
	protected void sequence_SQLDECLARATIONSBLOCK(ISerializationContext context, SQLDECLARATIONSBLOCK semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SQLFunction returns SQLFunction
	 *
	 * Constraint:
	 *     (name=STRING sqlFile=STRING)
	 */
	protected void sequence_SQLFunction(ISerializationContext context, SQLFunction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.SQL_FUNCTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.SQL_FUNCTION__NAME));
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.SQL_FUNCTION__SQL_FILE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.SQL_FUNCTION__SQL_FILE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSQLFunctionAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSQLFunctionAccess().getSqlFileSTRINGTerminalRuleCall_3_0(), semanticObject.getSqlFile());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Sequence returns Sequence
	 *
	 * Constraint:
	 *     (
	 *         name=FQN 
	 *         startWith=NATURAL? 
	 *         incrementBy=NATURAL? 
	 *         minValue=NATURAL? 
	 *         maxValue=NATURAL? 
	 *         cycle?='CYCLE'? 
	 *         cache=NATURAL?
	 *     )
	 */
	protected void sequence_Sequence(ISerializationContext context, Sequence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ShortCode returns ShortCode
	 *
	 * Constraint:
	 *     shortCodeValue=STRING
	 */
	protected void sequence_ShortCode(ISerializationContext context, ShortCode semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.SHORT_CODE__SHORT_CODE_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.SHORT_CODE__SHORT_CODE_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getShortCodeAccess().getShortCodeValueSTRINGTerminalRuleCall_1_0(), semanticObject.getShortCodeValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SqlFileDependency returns SqlFileDependency
	 *
	 * Constraint:
	 *     sqlFileDependency=STRING
	 */
	protected void sequence_SqlFileDependency(ISerializationContext context, SqlFileDependency semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.SQL_FILE_DEPENDENCY__SQL_FILE_DEPENDENCY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.SQL_FILE_DEPENDENCY__SQL_FILE_DEPENDENCY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSqlFileDependencyAccess().getSqlFileDependencySTRINGTerminalRuleCall_1_0(), semanticObject.getSqlFileDependency());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SqlNativeBlock returns SqlNativeBlock
	 *
	 * Constraint:
	 *     (
	 *         (
	 *             dbType='H2' | 
	 *             dbType='POSTGRESQL' | 
	 *             dbType='MYSQL' | 
	 *             dbType='SQLSERVER' | 
	 *             dbType='ORACLE' | 
	 *             dbType='DEFAULT'
	 *         ) 
	 *         sqlBlock=ML_SQLBLOCK
	 *     )
	 */
	protected void sequence_SqlNativeBlock(ISerializationContext context, SqlNativeBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SqlNative returns SqlNative
	 *
	 * Constraint:
	 *     (name=FQN? (sqlPosition='FILESTART' | sqlPosition='FILEEND')? sqlNativeBlocks+=SqlNativeBlock*)
	 */
	protected void sequence_SqlNative(ISerializationContext context, SqlNative semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DataTypeDefinition returns SubTypeDataType
	 *     SubTypeDataType returns SubTypeDataType
	 *
	 * Constraint:
	 *     (subTypeOf=[DataType|ID] ((length=NATURAL | maxlength?='MAX') scale=NATURAL?)?)
	 */
	protected void sequence_SubTypeDataType(ISerializationContext context, SubTypeDataType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     TableStereotype returns TableStereotype
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_TableStereotype(ISerializationContext context, TableStereotype semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetaDslPackage.Literals.TABLE_STEREOTYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetaDslPackage.Literals.TABLE_STEREOTYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTableStereotypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
