/*
 * generated by Xtext 2.20.0
 */
package com.jsantos.metadata.plugin;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import com.jsantos.metadata.plugin.naming.MetaDslDeclarativeQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetaDslRuntimeModule extends AbstractMetaDslRuntimeModule {

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return MetaDslDeclarativeQualifiedNameProvider.class;
	}
	
}
