package com.etantolling.testrunner.test.utils.misc;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringTokenizer;

public class SQLtoDTO {
	
	private static Map<String,String> TYPE_MAPPINGS = new HashMap<String,String>();
	static {
		TYPE_MAPPINGS.put("NUMBER", "Integer");
		TYPE_MAPPINGS.put("VARCHAR2", "String");
		TYPE_MAPPINGS.put("CHAR", "String");
		TYPE_MAPPINGS.put("DATE", "Date");
		TYPE_MAPPINGS.put("TIMESTAMP", "Date");
	}
	/*
	 * Tool to create the DTO for the huge tables used by the Image Review database, like TB_REQ_IN_DTL and TB_REQ_OUT_DTL
	 * 
	 * Go to SQL Plus or SQL Developer and do a DESC of the table you want to do the DTO for.
	 * 
	 * Paste the outcome in a text file, keeping the headers like this:
	 * Name             Null     Type          
		---------------- -------- ------------- 
		PK_N_USER_ID     NOT NULL NUMBER(10)    
		N_EMP_NUM        NOT NULL NUMBER(10)    
		VC_USER_NAME     NOT NULL VARCHAR2(30)  
		VC_USER_DESC     NOT NULL VARCHAR2(100) 
		VC_FIRST_NAME    NOT NULL VARCHAR2(50)  
		VC_LAST_NAME     NOT NULL VARCHAR2(50)  
		VC_EMAIL_ADDR    NOT NULL VARCHAR2(50)  
		VC_EMP_PHONE     NOT NULL VARCHAR2(20)  
		N_EMP_THEME      NOT NULL NUMBER(1)     
		N_IP_ROLE        NOT NULL NUMBER(2)     
		VC_USER_TYPE     NOT NULL VARCHAR2(1)   
		N_OCR_ENABLED    NOT NULL NUMBER(2)     
		VC_ACTIVE        NOT NULL VARCHAR2(1)   
		N_UPD_USER_ID    NOT NULL NUMBER(10)    
		TS_UPD_TIMESTAMP NOT NULL TIMESTAMP(3) 
		[...]
	 * 
	 * Run this tool with the text file as parameter and copy&paste the output in your DTO class
	 * Use the Eclipse "Generate Getters and Setters" to get the rest of the code based on the atributtes block generated by this tool.
	 * 
	 * The tool is homebrew stuff for developers: do not expect any fancy validation of parameters or exception handling = use at your own risk :-)
	 */
	public static void main(String[] args) throws Throwable {
		
		List<String> lines = Files.readAllLines(Paths.get(args[0]));
		// The second line would give us the width to use to split the content of the file in 3 columns
		String line = lines.get(1);

		int nullColumnStartIndex = line.indexOf(" ");
		int typeColumnStartIndex = line.indexOf(" ", nullColumnStartIndex+1);
		for (int i=2; i<lines.size(); i++) {
			line = lines.get(i);
			if (!line.isEmpty()) {	
				String name = line.substring(0, nullColumnStartIndex).trim();
				StringTokenizer st = new StringTokenizer(name, "_");
				name = st.nextToken().toLowerCase();
				while(st.hasMoreTokens()) {
					String nextToken = st.nextToken();
					name += nextToken.substring(0,1).toUpperCase();
					name += nextToken.substring(1).toLowerCase();
				}
				String type = TYPE_MAPPINGS.get(line.substring(typeColumnStartIndex).split("\\(")[0].trim());
				System.out.println( "private " + type + " " + name + ";" );
			}
		}
	}

}
