git checkout origin/postgres tutorial/poyake-tutorial-orm-simple/Test.png
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.updatesite/content.jar
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.updatesite/artifacts.jar
git checkout origin/postgres tutorial/poyake-tutorial-orm-simple/Test.png
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.updatesite/site.xml
git checkout origin/postgres  plugin/com.jsantos.metadata.plugin.updatesite/content.jar
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.updatesite/artifacts.jar
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.ui/src/com/jsantos/metadata/plugin/ui/grapheditor/serialization/Serializer.java
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.ui/src/com/jsantos/metadata/plugin/ui/grapheditor/GraphEditorPart.java
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.ui/src/com/jsantos/metadata/plugin/ui/grapheditor/GraphControls.java
git checkout origin/postgres plugin/com.jsantos.metadata.plugin.ui/plugin.xml
git checkout origin/postgres apps/poyake-testrunner/src-gen/com/jsantos/metadata/MTtestRunnerData.java
git checkout origin/postgres apps/poyake-demo-metadata/src-gen/com/jsantos/metadata/MT.java
