/*
 * generated by Xtext 2.20.0
 */
package com.jsantos.metadata.plugin.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class MetaDslScopeProvider extends AbstractMetaDslScopeProvider {
	
	public IScope getScope(EObject context, EReference ref) {
		//System.out.println("context " + context  + " feature " + ref.getFeatureID());
		//System.out.println("econtainer " + context.eContainer());
		//System.out.println("==================");
		

		IScope scope = super.getScope(context, ref);
		
		/*
		scope.getAllElements().forEach(e->{
			if (e.getEObjectURI().toString().contains("archive"))
				System.out.println("scope element " + e.getEObjectURI());
		});
		*/
		return scope;
	}

	@Override
	protected IScope delegateGetScope(EObject context, EReference reference) {
		// TODO Auto-generated method stub
		IScope scope = super.delegateGetScope(context, reference);
		/*
		scope.getAllElements().forEach(e->{
			if (e.getEObjectURI().toString().contains("archive")) {
				System.out.println("scope element " + e.getEObjectURI());
			}
		});
		*/
		return scope;
	}

	
	
}
