/*
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MetaDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/jsantos/metadata/plugin/parser/antlr/internal/InternalMetaDsl.tokens");
	}
}
