//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 12:40:34 PM CET 
//


package com.etantolling.testrunner.test.core.cli.configfolder.xmlbindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for host complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="host">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="config_folder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaults_config_folder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="environmentvariable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pathfragment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "host")
public class Host {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "config_folder")
    protected String configFolder;
    @XmlAttribute(name = "defaults_config_folder")
    protected String defaultsConfigFolder;
    @XmlAttribute(name = "username")
    protected String username;
    @XmlAttribute(name = "environmentvariable")
    protected String environmentvariable;
    @XmlAttribute(name = "pathfragment")
    protected String pathfragment;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the configFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigFolder() {
        return configFolder;
    }

    /**
     * Sets the value of the configFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigFolder(String value) {
        this.configFolder = value;
    }

    /**
     * Gets the value of the defaultsConfigFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultsConfigFolder() {
        return defaultsConfigFolder;
    }

    /**
     * Sets the value of the defaultsConfigFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultsConfigFolder(String value) {
        this.defaultsConfigFolder = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the environmentvariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentvariable() {
        return environmentvariable;
    }

    /**
     * Sets the value of the environmentvariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentvariable(String value) {
        this.environmentvariable = value;
    }

    /**
     * Gets the value of the pathfragment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathfragment() {
        return pathfragment;
    }

    /**
     * Sets the value of the pathfragment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathfragment(String value) {
        this.pathfragment = value;
    }

}
