//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 12:40:34 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/config_folder_map/")
package com.etantolling.testrunner.test.core.cli.configfolder.xmlbindings;
