/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getLanguages <em>Languages</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getDataTypes <em>Data Types</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getConstants <em>Constants</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getTableStereotypes <em>Table Stereotypes</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getColumnStereotypes <em>Column Stereotypes</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getPatterns <em>Patterns</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getDefaultPkGenerationStrategy <em>Default Pk Generation Strategy</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getMtClassName <em>Mt Class Name</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends EObject
{
  /**
   * Returns the value of the '<em><b>Languages</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Language}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Languages</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_Languages()
   * @model containment="true"
   * @generated
   */
  EList<Language> getLanguages();

  /**
   * Returns the value of the '<em><b>Data Types</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.DataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Types</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_DataTypes()
   * @model containment="true"
   * @generated
   */
  EList<DataType> getDataTypes();

  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_Constants()
   * @model containment="true"
   * @generated
   */
  EList<Constant> getConstants();

  /**
   * Returns the value of the '<em><b>Table Stereotypes</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.TableStereotype}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Stereotypes</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_TableStereotypes()
   * @model containment="true"
   * @generated
   */
  EList<TableStereotype> getTableStereotypes();

  /**
   * Returns the value of the '<em><b>Column Stereotypes</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.ColumnStereotype}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Stereotypes</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_ColumnStereotypes()
   * @model containment="true"
   * @generated
   */
  EList<ColumnStereotype> getColumnStereotypes();

  /**
   * Returns the value of the '<em><b>Patterns</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Pattern}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patterns</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_Patterns()
   * @model containment="true"
   * @generated
   */
  EList<Pattern> getPatterns();

  /**
   * Returns the value of the '<em><b>Default Pk Generation Strategy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Pk Generation Strategy</em>' attribute.
   * @see #setDefaultPkGenerationStrategy(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_DefaultPkGenerationStrategy()
   * @model
   * @generated
   */
  String getDefaultPkGenerationStrategy();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getDefaultPkGenerationStrategy <em>Default Pk Generation Strategy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Pk Generation Strategy</em>' attribute.
   * @see #getDefaultPkGenerationStrategy()
   * @generated
   */
  void setDefaultPkGenerationStrategy(String value);

  /**
   * Returns the value of the '<em><b>Mt Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mt Class Name</em>' attribute.
   * @see #setMtClassName(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getConfiguration_MtClassName()
   * @model
   * @generated
   */
  String getMtClassName();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Configuration#getMtClassName <em>Mt Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mt Class Name</em>' attribute.
   * @see #getMtClassName()
   * @generated
   */
  void setMtClassName(String value);

} // Configuration
