/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type Details</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#getDbNativeType <em>Db Native Type</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#isWithPrecissionAndScale <em>With Precission And Scale</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#isWithLength <em>With Length</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#getJavaType <em>Java Type</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDataTypeDetails()
 * @model
 * @generated
 */
public interface DataTypeDetails extends DataTypeDefinition
{
  /**
   * Returns the value of the '<em><b>Db Native Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Native Type</em>' attribute.
   * @see #setDbNativeType(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDataTypeDetails_DbNativeType()
   * @model
   * @generated
   */
  String getDbNativeType();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#getDbNativeType <em>Db Native Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Native Type</em>' attribute.
   * @see #getDbNativeType()
   * @generated
   */
  void setDbNativeType(String value);

  /**
   * Returns the value of the '<em><b>With Precission And Scale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Precission And Scale</em>' attribute.
   * @see #setWithPrecissionAndScale(boolean)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDataTypeDetails_WithPrecissionAndScale()
   * @model
   * @generated
   */
  boolean isWithPrecissionAndScale();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#isWithPrecissionAndScale <em>With Precission And Scale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With Precission And Scale</em>' attribute.
   * @see #isWithPrecissionAndScale()
   * @generated
   */
  void setWithPrecissionAndScale(boolean value);

  /**
   * Returns the value of the '<em><b>With Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Length</em>' attribute.
   * @see #setWithLength(boolean)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDataTypeDetails_WithLength()
   * @model
   * @generated
   */
  boolean isWithLength();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#isWithLength <em>With Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With Length</em>' attribute.
   * @see #isWithLength()
   * @generated
   */
  void setWithLength(boolean value);

  /**
   * Returns the value of the '<em><b>Java Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Type</em>' attribute.
   * @see #setJavaType(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDataTypeDetails_JavaType()
   * @model
   * @generated
   */
  String getJavaType();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails#getJavaType <em>Java Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Type</em>' attribute.
   * @see #getJavaType()
   * @generated
   */
  void setJavaType(String value);

} // DataTypeDetails
