/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Documentation Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.DocumentationSection#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.DocumentationSection#getDocumentationBlocks <em>Documentation Blocks</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDocumentationSection()
 * @model
 * @generated
 */
public interface DocumentationSection extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDocumentationSection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.DocumentationSection#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Documentation Blocks</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.DocumentationBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Documentation Blocks</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getDocumentationSection_DocumentationBlocks()
   * @model containment="true"
   * @generated
   */
  EList<DocumentationBlock> getDocumentationBlocks();

} // DocumentationSection
