/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enu Metadata</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.EnuMetadata#getEnuMetadataRows <em>Enu Metadata Rows</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getEnuMetadata()
 * @model
 * @generated
 */
public interface EnuMetadata extends EObject
{
  /**
   * Returns the value of the '<em><b>Enu Metadata Rows</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.EnuMetadataRow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enu Metadata Rows</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getEnuMetadata_EnuMetadataRows()
   * @model containment="true"
   * @generated
   */
  EList<EnuMetadataRow> getEnuMetadataRows();

} // EnuMetadata
