/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Id Generator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.IdGenerator#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.IdGenerator#getTypeBlock <em>Type Block</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getIdGenerator()
 * @model
 * @generated
 */
public interface IdGenerator extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getIdGenerator_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.IdGenerator#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Type Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Block</em>' containment reference.
   * @see #setTypeBlock(IdGeneratorTypeBlock)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getIdGenerator_TypeBlock()
   * @model containment="true"
   * @generated
   */
  IdGeneratorTypeBlock getTypeBlock();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.IdGenerator#getTypeBlock <em>Type Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Block</em>' containment reference.
   * @see #getTypeBlock()
   * @generated
   */
  void setTypeBlock(IdGeneratorTypeBlock value);

} // IdGenerator
