/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Label#getLang <em>Lang</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Label#getLabelText <em>Label Text</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabel()
 * @model
 * @generated
 */
public interface Label extends EObject
{
  /**
   * Returns the value of the '<em><b>Lang</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lang</em>' reference.
   * @see #setLang(Language)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabel_Lang()
   * @model
   * @generated
   */
  Language getLang();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Label#getLang <em>Lang</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lang</em>' reference.
   * @see #getLang()
   * @generated
   */
  void setLang(Language value);

  /**
   * Returns the value of the '<em><b>Label Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label Text</em>' attribute.
   * @see #setLabelText(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabel_LabelText()
   * @model
   * @generated
   */
  String getLabelText();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Label#getLabelText <em>Label Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label Text</em>' attribute.
   * @see #getLabelText()
   * @generated
   */
  void setLabelText(String value);

} // Label
