/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#isEntity <em>Entity</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#getType <em>Type</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#getLabels <em>Labels</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabelBlock()
 * @model
 * @generated
 */
public interface LabelBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' attribute.
   * @see #setEntity(boolean)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabelBlock_Entity()
   * @model
   * @generated
   */
  boolean isEntity();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#isEntity <em>Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' attribute.
   * @see #isEntity()
   * @generated
   */
  void setEntity(boolean value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabelBlock_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabelBlock_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Labels</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Label}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Labels</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getLabelBlock_Labels()
   * @model containment="true"
   * @generated
   */
  EList<Label> getLabels();

} // LabelBlock
