/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Metadata#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Metadata#getEntity <em>Entity</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Metadata#getMetadataRows <em>Metadata Rows</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadata()
 * @model
 * @generated
 */
public interface Metadata extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadata_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Metadata#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadata_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Metadata#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Metadata Rows</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.MetadataRow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata Rows</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadata_MetadataRows()
   * @model containment="true"
   * @generated
   */
  EList<MetadataRow> getMetadataRows();

} // Metadata
