/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata Row Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#getStringValue <em>String Value</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#getShortCode <em>Short Code</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#isIsNull <em>Is Null</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#isIsDefault <em>Is Default</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadataRowCell()
 * @model
 * @generated
 */
public interface MetadataRowCell extends EObject
{
  /**
   * Returns the value of the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Value</em>' attribute.
   * @see #setStringValue(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadataRowCell_StringValue()
   * @model
   * @generated
   */
  String getStringValue();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#getStringValue <em>String Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Value</em>' attribute.
   * @see #getStringValue()
   * @generated
   */
  void setStringValue(String value);

  /**
   * Returns the value of the '<em><b>Short Code</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short Code</em>' containment reference.
   * @see #setShortCode(ShortCode)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadataRowCell_ShortCode()
   * @model containment="true"
   * @generated
   */
  ShortCode getShortCode();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#getShortCode <em>Short Code</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short Code</em>' containment reference.
   * @see #getShortCode()
   * @generated
   */
  void setShortCode(ShortCode value);

  /**
   * Returns the value of the '<em><b>Is Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Null</em>' attribute.
   * @see #setIsNull(boolean)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadataRowCell_IsNull()
   * @model
   * @generated
   */
  boolean isIsNull();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#isIsNull <em>Is Null</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Null</em>' attribute.
   * @see #isIsNull()
   * @generated
   */
  void setIsNull(boolean value);

  /**
   * Returns the value of the '<em><b>Is Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Default</em>' attribute.
   * @see #setIsDefault(boolean)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getMetadataRowCell_IsDefault()
   * @model
   * @generated
   */
  boolean isIsDefault();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell#isIsDefault <em>Is Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Default</em>' attribute.
   * @see #isIsDefault()
   * @generated
   */
  void setIsDefault(boolean value);

} // MetadataRowCell
