/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Model#getEntities <em>Entities</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Model#getSequences <em>Sequences</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Model#getConfiguration <em>Configuration</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Model#getGeneralLabelSection <em>General Label Section</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Model#getSqlNatives <em>Sql Natives</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Model#getMetadatas <em>Metadatas</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Sequences</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Sequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequences</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel_Sequences()
   * @model containment="true"
   * @generated
   */
  EList<Sequence> getSequences();

  /**
   * Returns the value of the '<em><b>Configuration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configuration</em>' containment reference.
   * @see #setConfiguration(Configuration)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel_Configuration()
   * @model containment="true"
   * @generated
   */
  Configuration getConfiguration();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Model#getConfiguration <em>Configuration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Configuration</em>' containment reference.
   * @see #getConfiguration()
   * @generated
   */
  void setConfiguration(Configuration value);

  /**
   * Returns the value of the '<em><b>General Label Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>General Label Section</em>' containment reference.
   * @see #setGeneralLabelSection(GeneralLabelSection)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel_GeneralLabelSection()
   * @model containment="true"
   * @generated
   */
  GeneralLabelSection getGeneralLabelSection();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Model#getGeneralLabelSection <em>General Label Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>General Label Section</em>' containment reference.
   * @see #getGeneralLabelSection()
   * @generated
   */
  void setGeneralLabelSection(GeneralLabelSection value);

  /**
   * Returns the value of the '<em><b>Sql Natives</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.SqlNative}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql Natives</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel_SqlNatives()
   * @model containment="true"
   * @generated
   */
  EList<SqlNative> getSqlNatives();

  /**
   * Returns the value of the '<em><b>Metadatas</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Metadata}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadatas</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getModel_Metadatas()
   * @model containment="true"
   * @generated
   */
  EList<Metadata> getMetadatas();

} // Model
