/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Override Label Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getEntity <em>Entity</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getEnuMetadataRow <em>Enu Metadata Row</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getType <em>Type</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getLabels <em>Labels</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getOverrideLabelBlock()
 * @model
 * @generated
 */
public interface OverrideLabelBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getOverrideLabelBlock_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getOverrideLabelBlock_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Enu Metadata Row</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enu Metadata Row</em>' reference.
   * @see #setEnuMetadataRow(EnuMetadataRow)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getOverrideLabelBlock_EnuMetadataRow()
   * @model
   * @generated
   */
  EnuMetadataRow getEnuMetadataRow();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getEnuMetadataRow <em>Enu Metadata Row</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enu Metadata Row</em>' reference.
   * @see #getEnuMetadataRow()
   * @generated
   */
  void setEnuMetadataRow(EnuMetadataRow value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getOverrideLabelBlock_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Labels</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.Label}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Labels</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getOverrideLabelBlock_Labels()
   * @model containment="true"
   * @generated
   */
  EList<Label> getLabels();

} // OverrideLabelBlock
