/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Source Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.QuerySourceBlock#getQuerySource <em>Query Source</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getQuerySourceBlock()
 * @model
 * @generated
 */
public interface QuerySourceBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Query Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query Source</em>' attribute.
   * @see #setQuerySource(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getQuerySourceBlock_QuerySource()
   * @model
   * @generated
   */
  String getQuerySource();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.QuerySourceBlock#getQuerySource <em>Query Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query Source</em>' attribute.
   * @see #getQuerySource()
   * @generated
   */
  void setQuerySource(String value);

} // QuerySourceBlock
