/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getStartWith <em>Start With</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getIncrementBy <em>Increment By</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getMinValue <em>Min Value</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getMaxValue <em>Max Value</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#isCycle <em>Cycle</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getCache <em>Cache</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence()
 * @model
 * @generated
 */
public interface Sequence extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Start With</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start With</em>' attribute.
   * @see #setStartWith(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_StartWith()
   * @model
   * @generated
   */
  String getStartWith();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getStartWith <em>Start With</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start With</em>' attribute.
   * @see #getStartWith()
   * @generated
   */
  void setStartWith(String value);

  /**
   * Returns the value of the '<em><b>Increment By</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Increment By</em>' attribute.
   * @see #setIncrementBy(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_IncrementBy()
   * @model
   * @generated
   */
  String getIncrementBy();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getIncrementBy <em>Increment By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Increment By</em>' attribute.
   * @see #getIncrementBy()
   * @generated
   */
  void setIncrementBy(String value);

  /**
   * Returns the value of the '<em><b>Min Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Value</em>' attribute.
   * @see #setMinValue(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_MinValue()
   * @model
   * @generated
   */
  String getMinValue();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getMinValue <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Value</em>' attribute.
   * @see #getMinValue()
   * @generated
   */
  void setMinValue(String value);

  /**
   * Returns the value of the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Value</em>' attribute.
   * @see #setMaxValue(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_MaxValue()
   * @model
   * @generated
   */
  String getMaxValue();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getMaxValue <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Value</em>' attribute.
   * @see #getMaxValue()
   * @generated
   */
  void setMaxValue(String value);

  /**
   * Returns the value of the '<em><b>Cycle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cycle</em>' attribute.
   * @see #setCycle(boolean)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_Cycle()
   * @model
   * @generated
   */
  boolean isCycle();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#isCycle <em>Cycle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cycle</em>' attribute.
   * @see #isCycle()
   * @generated
   */
  void setCycle(boolean value);

  /**
   * Returns the value of the '<em><b>Cache</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cache</em>' attribute.
   * @see #setCache(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSequence_Cache()
   * @model
   * @generated
   */
  String getCache();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.Sequence#getCache <em>Cache</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cache</em>' attribute.
   * @see #getCache()
   * @generated
   */
  void setCache(String value);

} // Sequence
