/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Short Code</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.ShortCode#getShortCodeValue <em>Short Code Value</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getShortCode()
 * @model
 * @generated
 */
public interface ShortCode extends EObject
{
  /**
   * Returns the value of the '<em><b>Short Code Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short Code Value</em>' attribute.
   * @see #setShortCodeValue(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getShortCode_ShortCodeValue()
   * @model
   * @generated
   */
  String getShortCodeValue();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.ShortCode#getShortCodeValue <em>Short Code Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short Code Value</em>' attribute.
   * @see #getShortCodeValue()
   * @generated
   */
  void setShortCodeValue(String value);

} // ShortCode
