/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SQLDECLARATIONSBLOCK</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.SQLDECLARATIONSBLOCK#getSqlFunctions <em>Sql Functions</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSQLDECLARATIONSBLOCK()
 * @model
 * @generated
 */
public interface SQLDECLARATIONSBLOCK extends EObject
{
  /**
   * Returns the value of the '<em><b>Sql Functions</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.SQLFunction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql Functions</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSQLDECLARATIONSBLOCK_SqlFunctions()
   * @model containment="true"
   * @generated
   */
  EList<SQLFunction> getSqlFunctions();

} // SQLDECLARATIONSBLOCK
