/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sql File Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.SqlFileDependency#getSqlFileDependency <em>Sql File Dependency</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSqlFileDependency()
 * @model
 * @generated
 */
public interface SqlFileDependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Sql File Dependency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql File Dependency</em>' attribute.
   * @see #setSqlFileDependency(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSqlFileDependency_SqlFileDependency()
   * @model
   * @generated
   */
  String getSqlFileDependency();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.SqlFileDependency#getSqlFileDependency <em>Sql File Dependency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sql File Dependency</em>' attribute.
   * @see #getSqlFileDependency()
   * @generated
   */
  void setSqlFileDependency(String value);

} // SqlFileDependency
