/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sql Native</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.SqlNative#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.SqlNative#getSqlPosition <em>Sql Position</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.SqlNative#getSqlNativeBlocks <em>Sql Native Blocks</em>}</li>
 * </ul>
 *
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSqlNative()
 * @model
 * @generated
 */
public interface SqlNative extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSqlNative_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.SqlNative#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sql Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql Position</em>' attribute.
   * @see #setSqlPosition(String)
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSqlNative_SqlPosition()
   * @model
   * @generated
   */
  String getSqlPosition();

  /**
   * Sets the value of the '{@link com.jsantos.metadata.plugin.metaDsl.SqlNative#getSqlPosition <em>Sql Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sql Position</em>' attribute.
   * @see #getSqlPosition()
   * @generated
   */
  void setSqlPosition(String value);

  /**
   * Returns the value of the '<em><b>Sql Native Blocks</b></em>' containment reference list.
   * The list contents are of type {@link com.jsantos.metadata.plugin.metaDsl.SqlNativeBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql Native Blocks</em>' containment reference list.
   * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage#getSqlNative_SqlNativeBlocks()
   * @model containment="true"
   * @generated
   */
  EList<SqlNativeBlock> getSqlNativeBlocks();

} // SqlNative
