/*
 * generated by Xtext 2.20.0
 */
package com.jsantos.metadata.plugin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;

import com.jsantos.metadata.plugin.ui.builder.JavaProjectBasedBuilderParticipant2;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MetaDslUiModule extends AbstractMetaDslUiModule {
	
	public MetaDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
    @Override
    public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
        return JavaProjectBasedBuilderParticipant2.class;
    }

	@Override
	public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
		// TODO Auto-generated method stub
		return super.bindIResourceSetProvider();
	}	
    
    
}
