package com.jsantos.metadata;

import com.jsantos.orm.mt.MTBase; 
import com.jsantos.metadata.common.*;
import com.jsantos.metadata.audit.*;
import com.jsantos.metadata.config.*;
import com.jsantos.metadata.label.*;

public class MTTemplateData extends MTBase{ 
	static boolean initialized = false;

	public static MTTableENUTEMPLATETYPE ENUTEMPLATETYPE;
	public static MTTableTEMPLATE TEMPLATE;
	public static MTTableINPUTSOURCE INPUTSOURCE;
	public static MTTableINPUTUSER INPUTUSER;
	public static MTTableINPUTUSERGROUP INPUTUSERGROUP;
	public static MTTableUSERGROUP USERGROUP;
	public static MTTableVUSERMULTIGROUP VUSERMULTIGROUP;
	public static MTTableVINPUTUSER VINPUTUSER;
	public static MTTableVINPUTUSERMULTI VINPUTUSERMULTI;
	public static MTTableVUSERGROUP VUSERGROUP;
	public static MTTableAPPDATATYPE APPDATATYPE;
	public static MTTableAPPINFO APPINFO;
	public static MTTableAPPINFOTREE APPINFOTREE;
	public static MTTablePOSTINGDATE POSTINGDATE;
	public static MTTableENULOCALE ENULOCALE;
	public static MTTableMTLABEL MTLABEL;

	public static void init(){
		if (initialized) return;
		initialized = true;

		MTTemplateData.init();
		MTAuditData.init();
		MTLabelData.init();
		ENUTEMPLATETYPE = new MTTableENUTEMPLATETYPE();
		TEMPLATE = new MTTableTEMPLATE();
		INPUTSOURCE = new MTTableINPUTSOURCE();
		INPUTUSER = new MTTableINPUTUSER();
		INPUTUSERGROUP = new MTTableINPUTUSERGROUP();
		USERGROUP = new MTTableUSERGROUP();
		VUSERMULTIGROUP = new MTTableVUSERMULTIGROUP();
		VINPUTUSER = new MTTableVINPUTUSER();
		VINPUTUSERMULTI = new MTTableVINPUTUSERMULTI();
		VUSERGROUP = new MTTableVUSERGROUP();
		APPDATATYPE = new MTTableAPPDATATYPE();
		APPINFO = new MTTableAPPINFO();
		APPINFOTREE = new MTTableAPPINFOTREE();
		POSTINGDATE = new MTTablePOSTINGDATE();
		ENULOCALE = new MTTableENULOCALE();
		MTLABEL = new MTTableMTLABEL();

		tables.put("ENUTEMPLATETYPE", ENUTEMPLATETYPE);
		tables.put("TEMPLATE", TEMPLATE);
		tables.put("INPUTSOURCE", INPUTSOURCE);
		tables.put("INPUTUSER", INPUTUSER);
		tables.put("INPUTUSERGROUP", INPUTUSERGROUP);
		tables.put("USERGROUP", USERGROUP);
		tables.put("VUSERMULTIGROUP", VUSERMULTIGROUP);
		tables.put("VINPUTUSER", VINPUTUSER);
		tables.put("VINPUTUSERMULTI", VINPUTUSERMULTI);
		tables.put("VUSERGROUP", VUSERGROUP);
		tables.put("APPDATATYPE", APPDATATYPE);
		tables.put("APPINFO", APPINFO);
		tables.put("APPINFOTREE", APPINFOTREE);
		tables.put("POSTINGDATE", POSTINGDATE);
		tables.put("ENULOCALE", ENULOCALE);
		tables.put("MTLABEL", MTLABEL);

		MTTableTEMPLATE.ENUTEMPLATETYPEID.setForeignKey(ENUTEMPLATETYPE);
		MTTableTEMPLATE.ENULOCALEID.setForeignKey(ENULOCALE);
		MTTableTEMPLATE.INPUTUSERID.setForeignKey(INPUTUSER);
		MTTableTEMPLATE.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableINPUTUSER.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableUSERGROUP.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableUSERGROUP.USERID.setForeignKey(INPUTUSER);
		MTTableUSERGROUP.INPUTUSERID.setForeignKey(INPUTUSER);
		MTTableUSERGROUP.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableVUSERMULTIGROUP.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableVUSERMULTIGROUP.USERGROUPS.setMultiRefTo(USERGROUP);
		MTTableVINPUTUSER.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableVINPUTUSERMULTI.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableVINPUTUSERMULTI.USERGROUPS.setMultiRefTo(USERGROUP);
		MTTableVUSERGROUP.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableVUSERGROUP.USERID.setForeignKey(INPUTUSER);
		MTTableVUSERGROUP.INPUTUSERID.setForeignKey(INPUTUSER);
		MTTableVUSERGROUP.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableAPPINFO.TYPE.setForeignKey(APPDATATYPE);
		MTTableAPPINFO.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableAPPINFOTREE.PARENTAPPINFOTREEID.setForeignKey(APPINFOTREE);
		MTTableAPPINFOTREE.APPINFOID.setForeignKey(APPINFO);

	}
} 

