/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.util;

import com.jsantos.metadata.plugin.metaDsl.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see com.jsantos.metadata.plugin.metaDsl.MetaDslPackage
 * @generated
 */
public class MetaDslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MetaDslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MetaDslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = MetaDslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetaDslSwitch<Adapter> modelSwitch =
    new MetaDslSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseConfiguration(Configuration object)
      {
        return createConfigurationAdapter();
      }
      @Override
      public Adapter caseLanguage(Language object)
      {
        return createLanguageAdapter();
      }
      @Override
      public Adapter caseConstant(Constant object)
      {
        return createConstantAdapter();
      }
      @Override
      public Adapter caseDataType(DataType object)
      {
        return createDataTypeAdapter();
      }
      @Override
      public Adapter caseDataTypeDefinition(DataTypeDefinition object)
      {
        return createDataTypeDefinitionAdapter();
      }
      @Override
      public Adapter caseDataTypeDetails(DataTypeDetails object)
      {
        return createDataTypeDetailsAdapter();
      }
      @Override
      public Adapter caseSubTypeDataType(SubTypeDataType object)
      {
        return createSubTypeDataTypeAdapter();
      }
      @Override
      public Adapter caseTableStereotype(TableStereotype object)
      {
        return createTableStereotypeAdapter();
      }
      @Override
      public Adapter caseColumnStereotype(ColumnStereotype object)
      {
        return createColumnStereotypeAdapter();
      }
      @Override
      public Adapter casePattern(Pattern object)
      {
        return createPatternAdapter();
      }
      @Override
      public Adapter caseEntity(Entity object)
      {
        return createEntityAdapter();
      }
      @Override
      public Adapter caseSqlFileDependency(SqlFileDependency object)
      {
        return createSqlFileDependencyAdapter();
      }
      @Override
      public Adapter caseSequence(Sequence object)
      {
        return createSequenceAdapter();
      }
      @Override
      public Adapter caseAttribute(Attribute object)
      {
        return createAttributeAdapter();
      }
      @Override
      public Adapter caseIdGenerator(IdGenerator object)
      {
        return createIdGeneratorAdapter();
      }
      @Override
      public Adapter caseIdGeneratorTypeBlock(IdGeneratorTypeBlock object)
      {
        return createIdGeneratorTypeBlockAdapter();
      }
      @Override
      public Adapter caseIdGeneratorSimple(IdGeneratorSimple object)
      {
        return createIdGeneratorSimpleAdapter();
      }
      @Override
      public Adapter caseIdGeneratorSequence(IdGeneratorSequence object)
      {
        return createIdGeneratorSequenceAdapter();
      }
      @Override
      public Adapter caseEnuMetadata(EnuMetadata object)
      {
        return createEnuMetadataAdapter();
      }
      @Override
      public Adapter caseEnuMetadataRow(EnuMetadataRow object)
      {
        return createEnuMetadataRowAdapter();
      }
      @Override
      public Adapter caseMetadata(Metadata object)
      {
        return createMetadataAdapter();
      }
      @Override
      public Adapter caseShortCode(ShortCode object)
      {
        return createShortCodeAdapter();
      }
      @Override
      public Adapter caseMetadataRow(MetadataRow object)
      {
        return createMetadataRowAdapter();
      }
      @Override
      public Adapter caseMetadataRowCell(MetadataRowCell object)
      {
        return createMetadataRowCellAdapter();
      }
      @Override
      public Adapter caseLabelSection(LabelSection object)
      {
        return createLabelSectionAdapter();
      }
      @Override
      public Adapter caseLabelBlock(LabelBlock object)
      {
        return createLabelBlockAdapter();
      }
      @Override
      public Adapter caseGeneralLabelSection(GeneralLabelSection object)
      {
        return createGeneralLabelSectionAdapter();
      }
      @Override
      public Adapter caseKeyLabel(KeyLabel object)
      {
        return createKeyLabelAdapter();
      }
      @Override
      public Adapter caseOverrideLabelBlock(OverrideLabelBlock object)
      {
        return createOverrideLabelBlockAdapter();
      }
      @Override
      public Adapter caseEnumerationLabels(EnumerationLabels object)
      {
        return createEnumerationLabelsAdapter();
      }
      @Override
      public Adapter caseEnumerationLabel(EnumerationLabel object)
      {
        return createEnumerationLabelAdapter();
      }
      @Override
      public Adapter caseLabel(Label object)
      {
        return createLabelAdapter();
      }
      @Override
      public Adapter caseDocumentationSection(DocumentationSection object)
      {
        return createDocumentationSectionAdapter();
      }
      @Override
      public Adapter caseDocumentationBlock(DocumentationBlock object)
      {
        return createDocumentationBlockAdapter();
      }
      @Override
      public Adapter caseQuerySourceBlock(QuerySourceBlock object)
      {
        return createQuerySourceBlockAdapter();
      }
      @Override
      public Adapter caseSQLDECLARATIONSBLOCK(SQLDECLARATIONSBLOCK object)
      {
        return createSQLDECLARATIONSBLOCKAdapter();
      }
      @Override
      public Adapter caseSQLFunction(SQLFunction object)
      {
        return createSQLFunctionAdapter();
      }
      @Override
      public Adapter caseSqlNative(SqlNative object)
      {
        return createSqlNativeAdapter();
      }
      @Override
      public Adapter caseSqlNativeBlock(SqlNativeBlock object)
      {
        return createSqlNativeBlockAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Configuration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Configuration
   * @generated
   */
  public Adapter createConfigurationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Language <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Language
   * @generated
   */
  public Adapter createLanguageAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Constant
   * @generated
   */
  public Adapter createConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.DataType
   * @generated
   */
  public Adapter createDataTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDefinition <em>Data Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.DataTypeDefinition
   * @generated
   */
  public Adapter createDataTypeDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.DataTypeDetails <em>Data Type Details</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.DataTypeDetails
   * @generated
   */
  public Adapter createDataTypeDetailsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.SubTypeDataType <em>Sub Type Data Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.SubTypeDataType
   * @generated
   */
  public Adapter createSubTypeDataTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.TableStereotype <em>Table Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.TableStereotype
   * @generated
   */
  public Adapter createTableStereotypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.ColumnStereotype <em>Column Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.ColumnStereotype
   * @generated
   */
  public Adapter createColumnStereotypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Pattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Pattern
   * @generated
   */
  public Adapter createPatternAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Entity
   * @generated
   */
  public Adapter createEntityAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.SqlFileDependency <em>Sql File Dependency</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.SqlFileDependency
   * @generated
   */
  public Adapter createSqlFileDependencyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Sequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Sequence
   * @generated
   */
  public Adapter createSequenceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Attribute
   * @generated
   */
  public Adapter createAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.IdGenerator <em>Id Generator</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.IdGenerator
   * @generated
   */
  public Adapter createIdGeneratorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.IdGeneratorTypeBlock <em>Id Generator Type Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.IdGeneratorTypeBlock
   * @generated
   */
  public Adapter createIdGeneratorTypeBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.IdGeneratorSimple <em>Id Generator Simple</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.IdGeneratorSimple
   * @generated
   */
  public Adapter createIdGeneratorSimpleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.IdGeneratorSequence <em>Id Generator Sequence</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.IdGeneratorSequence
   * @generated
   */
  public Adapter createIdGeneratorSequenceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.EnuMetadata <em>Enu Metadata</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.EnuMetadata
   * @generated
   */
  public Adapter createEnuMetadataAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.EnuMetadataRow <em>Enu Metadata Row</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.EnuMetadataRow
   * @generated
   */
  public Adapter createEnuMetadataRowAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Metadata <em>Metadata</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Metadata
   * @generated
   */
  public Adapter createMetadataAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.ShortCode <em>Short Code</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.ShortCode
   * @generated
   */
  public Adapter createShortCodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.MetadataRow <em>Metadata Row</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.MetadataRow
   * @generated
   */
  public Adapter createMetadataRowAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.MetadataRowCell <em>Metadata Row Cell</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.MetadataRowCell
   * @generated
   */
  public Adapter createMetadataRowCellAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.LabelSection <em>Label Section</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.LabelSection
   * @generated
   */
  public Adapter createLabelSectionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.LabelBlock <em>Label Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.LabelBlock
   * @generated
   */
  public Adapter createLabelBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.GeneralLabelSection <em>General Label Section</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.GeneralLabelSection
   * @generated
   */
  public Adapter createGeneralLabelSectionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.KeyLabel <em>Key Label</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.KeyLabel
   * @generated
   */
  public Adapter createKeyLabelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock <em>Override Label Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock
   * @generated
   */
  public Adapter createOverrideLabelBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.EnumerationLabels <em>Enumeration Labels</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.EnumerationLabels
   * @generated
   */
  public Adapter createEnumerationLabelsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.EnumerationLabel <em>Enumeration Label</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.EnumerationLabel
   * @generated
   */
  public Adapter createEnumerationLabelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.Label
   * @generated
   */
  public Adapter createLabelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.DocumentationSection <em>Documentation Section</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.DocumentationSection
   * @generated
   */
  public Adapter createDocumentationSectionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.DocumentationBlock <em>Documentation Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.DocumentationBlock
   * @generated
   */
  public Adapter createDocumentationBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.QuerySourceBlock <em>Query Source Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.QuerySourceBlock
   * @generated
   */
  public Adapter createQuerySourceBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.SQLDECLARATIONSBLOCK <em>SQLDECLARATIONSBLOCK</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.SQLDECLARATIONSBLOCK
   * @generated
   */
  public Adapter createSQLDECLARATIONSBLOCKAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.SQLFunction <em>SQL Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.SQLFunction
   * @generated
   */
  public Adapter createSQLFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.SqlNative <em>Sql Native</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.SqlNative
   * @generated
   */
  public Adapter createSqlNativeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.jsantos.metadata.plugin.metaDsl.SqlNativeBlock <em>Sql Native Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.jsantos.metadata.plugin.metaDsl.SqlNativeBlock
   * @generated
   */
  public Adapter createSqlNativeBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //MetaDslAdapterFactory
