/*
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMetaDslScopeProvider extends DelegatingScopeProvider {
}
