package com.jsantos.metadata.tolling;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import com.jsantos.orm.mt.MTEnumeration;
import com.jsantos.orm.label.Label;

public class EnuLicensePlateJurisdiction extends MTEnumeration{
	static protected LinkedHashMap<Integer, String> values = new LinkedHashMap<>();
	static protected LinkedHashMap<String, Integer> shortCodes = new LinkedHashMap<>();
	static protected LinkedHashMap<Integer, ArrayList<Label>> labels = new LinkedHashMap<>();

	public static final int xx = 0;
	public static final int AL = 1;
	public static final int AK = 2;
	public static final int AZ = 3;
	public static final int AR = 4;
	public static final int CA = 5;
	public static final int CO = 6;
	public static final int CT = 7;
	public static final int DE = 8;
	public static final int FL = 9;
	public static final int GA = 10;
	public static final int HI = 11;
	public static final int IDH = 12;
	public static final int IL = 13;
	public static final int IN = 14;
	public static final int IA = 15;
	public static final int KS = 16;
	public static final int KY = 17;
	public static final int LA = 18;
	public static final int ME = 19;
	public static final int MD = 20;
	public static final int MA = 21;
	public static final int MI = 22;
	public static final int MN = 23;
	public static final int MS = 24;
	public static final int MO = 25;
	public static final int MT = 26;
	public static final int NE = 27;
	public static final int NV = 28;
	public static final int NH = 29;
	public static final int NJ = 30;
	public static final int NM = 31;
	public static final int NY = 32;
	public static final int NC = 33;
	public static final int ND = 34;
	public static final int OH = 35;
	public static final int OK = 36;
	public static final int OR = 37;
	public static final int PA = 38;
	public static final int RI = 39;
	public static final int SC = 40;
	public static final int SD = 41;
	public static final int TN = 42;
	public static final int TX = 43;
	public static final int UT = 44;
	public static final int VT = 45;
	public static final int VA = 46;
	public static final int WA = 47;
	public static final int WV = 48;
	public static final int WI = 49;
	public static final int WY = 50;
	public static final int AB = 51;
	public static final int BC = 52;
	public static final int MB = 53;
	public static final int NB = 54;
	public static final int NL = 55;
	public static final int NS = 56;
	public static final int NT = 57;
	public static final int NU = 58;
	public static final int ON = 59;
	public static final int PE = 60;
	public static final int QC = 61;
	public static final int SK = 62;
	public static final int YT = 63;
	public static final int AGU = 64;
	public static final int BCN = 65;
	public static final int BCS = 66;
	public static final int CAM = 67;
	public static final int CHP = 68;
	public static final int CHH = 69;
	public static final int COA = 70;
	public static final int COL = 71;
	public static final int CMX = 72;
	public static final int DUR = 73;
	public static final int GUA = 74;
	public static final int GRO = 75;
	public static final int HID = 76;
	public static final int JAL = 77;
	public static final int MEX = 78;
	public static final int MIC = 79;
	public static final int MOR = 80;
	public static final int NAY = 81;
	public static final int NLE = 82;
	public static final int OAX = 83;
	public static final int PUE = 84;
	public static final int QUE = 85;
	public static final int ROO = 86;
	public static final int SLP = 87;
	public static final int SIN = 88;
	public static final int SON = 89;
	public static final int TAB = 90;
	public static final int TAM = 91;
	public static final int TLA = 92;
	public static final int VER = 93;
	public static final int YUC = 94;
	public static final int ZAC = 95;
	public static final int DC = 96;
	public static final int AS = 97;
	public static final int FM = 98;
	public static final int GU = 99;
	public static final int MH = 100;
	public static final int MP = 101;
	public static final int PW = 102;
	public static final int PR = 103;
	public static final int VI = 104;
	public static final int LB = 105;
	public static final int PQ = 106;
	public static final int AA = 108;
	public static final int AE = 109;
	public static final int AP = 110;
	public static final int II = 111;
	public static final int DHS = 1000;
	public static final int FD = 1001;
	public static final int GSA = 1002;
	public static final int DL = 1003;
	public static final int FC = 1004;
	public static final int PUY = 1005;
	public static final int CLV = 1006;
	public static final int LUM = 1007;
	public static final int SPK = 1008;
	public static final int QIN = 1009;
	public static final int MCK = 1010;
	public static final int TUL = 1011;
	public static final int YAK = 1012;

	static {
		values.put(0,"Unknown");
		shortCodes.put("xx",0);
		labels.put(0, new ArrayList<Label>());
		values.put(1,"Alabama");
		shortCodes.put("AL",1);
		labels.put(1, new ArrayList<Label>());
		values.put(2,"Alaska");
		shortCodes.put("AK",2);
		labels.put(2, new ArrayList<Label>());
		values.put(3,"Arizona");
		shortCodes.put("AZ",3);
		labels.put(3, new ArrayList<Label>());
		values.put(4,"Arkansas");
		shortCodes.put("AR",4);
		labels.put(4, new ArrayList<Label>());
		values.put(5,"California");
		shortCodes.put("CA",5);
		labels.put(5, new ArrayList<Label>());
		values.put(6,"Colorado");
		shortCodes.put("CO",6);
		labels.put(6, new ArrayList<Label>());
		values.put(7,"Connecticut");
		shortCodes.put("CT",7);
		labels.put(7, new ArrayList<Label>());
		values.put(8,"Delaware");
		shortCodes.put("DE",8);
		labels.put(8, new ArrayList<Label>());
		values.put(9,"Florida");
		shortCodes.put("FL",9);
		labels.put(9, new ArrayList<Label>());
		values.put(10,"Georgia");
		shortCodes.put("GA",10);
		labels.put(10, new ArrayList<Label>());
		values.put(11,"Hawaii");
		shortCodes.put("HI",11);
		labels.put(11, new ArrayList<Label>());
		values.put(12,"Idaho");
		shortCodes.put("IDH",12);
		labels.put(12, new ArrayList<Label>());
		values.put(13,"Illinois");
		shortCodes.put("IL",13);
		labels.put(13, new ArrayList<Label>());
		values.put(14,"Indiana");
		shortCodes.put("IN",14);
		labels.put(14, new ArrayList<Label>());
		values.put(15,"Iowa");
		shortCodes.put("IA",15);
		labels.put(15, new ArrayList<Label>());
		values.put(16,"Kansas");
		shortCodes.put("KS",16);
		labels.put(16, new ArrayList<Label>());
		values.put(17,"Kentucky");
		shortCodes.put("KY",17);
		labels.put(17, new ArrayList<Label>());
		values.put(18,"Lousiana");
		shortCodes.put("LA",18);
		labels.put(18, new ArrayList<Label>());
		values.put(19,"Maine");
		shortCodes.put("ME",19);
		labels.put(19, new ArrayList<Label>());
		values.put(20,"Maryland");
		shortCodes.put("MD",20);
		labels.put(20, new ArrayList<Label>());
		values.put(21,"Massachusetts");
		shortCodes.put("MA",21);
		labels.put(21, new ArrayList<Label>());
		values.put(22,"Michigan");
		shortCodes.put("MI",22);
		labels.put(22, new ArrayList<Label>());
		values.put(23,"Minnesota");
		shortCodes.put("MN",23);
		labels.put(23, new ArrayList<Label>());
		values.put(24,"Mississippi");
		shortCodes.put("MS",24);
		labels.put(24, new ArrayList<Label>());
		values.put(25,"Missouri");
		shortCodes.put("MO",25);
		labels.put(25, new ArrayList<Label>());
		values.put(26,"Montana");
		shortCodes.put("MT",26);
		labels.put(26, new ArrayList<Label>());
		values.put(27,"Nebraska");
		shortCodes.put("NE",27);
		labels.put(27, new ArrayList<Label>());
		values.put(28,"Nevada");
		shortCodes.put("NV",28);
		labels.put(28, new ArrayList<Label>());
		values.put(29,"New Hampshire");
		shortCodes.put("NH",29);
		labels.put(29, new ArrayList<Label>());
		values.put(30,"New Jersey");
		shortCodes.put("NJ",30);
		labels.put(30, new ArrayList<Label>());
		values.put(31,"New Mexico");
		shortCodes.put("NM",31);
		labels.put(31, new ArrayList<Label>());
		values.put(32,"New York");
		shortCodes.put("NY",32);
		labels.put(32, new ArrayList<Label>());
		values.put(33,"North Carolina");
		shortCodes.put("NC",33);
		labels.put(33, new ArrayList<Label>());
		values.put(34,"North Dakota");
		shortCodes.put("ND",34);
		labels.put(34, new ArrayList<Label>());
		values.put(35,"Ohio");
		shortCodes.put("OH",35);
		labels.put(35, new ArrayList<Label>());
		values.put(36,"Oklahoma");
		shortCodes.put("OK",36);
		labels.put(36, new ArrayList<Label>());
		values.put(37,"Oregon");
		shortCodes.put("OR",37);
		labels.put(37, new ArrayList<Label>());
		values.put(38,"Pennsylvania");
		shortCodes.put("PA",38);
		labels.put(38, new ArrayList<Label>());
		values.put(39,"Rhode Island");
		shortCodes.put("RI",39);
		labels.put(39, new ArrayList<Label>());
		values.put(40,"South Carolina");
		shortCodes.put("SC",40);
		labels.put(40, new ArrayList<Label>());
		values.put(41,"South Dakota");
		shortCodes.put("SD",41);
		labels.put(41, new ArrayList<Label>());
		values.put(42,"Tennessee");
		shortCodes.put("TN",42);
		labels.put(42, new ArrayList<Label>());
		values.put(43,"Texas");
		shortCodes.put("TX",43);
		labels.put(43, new ArrayList<Label>());
		values.put(44,"Utah");
		shortCodes.put("UT",44);
		labels.put(44, new ArrayList<Label>());
		values.put(45,"Vermont");
		shortCodes.put("VT",45);
		labels.put(45, new ArrayList<Label>());
		values.put(46,"Virginia");
		shortCodes.put("VA",46);
		labels.put(46, new ArrayList<Label>());
		values.put(47,"Washington");
		shortCodes.put("WA",47);
		labels.put(47, new ArrayList<Label>());
		values.put(48,"West Virginia");
		shortCodes.put("WV",48);
		labels.put(48, new ArrayList<Label>());
		values.put(49,"Wisconsin");
		shortCodes.put("WI",49);
		labels.put(49, new ArrayList<Label>());
		values.put(50,"Wyoming");
		shortCodes.put("WY",50);
		labels.put(50, new ArrayList<Label>());
		values.put(51,"Alberta");
		shortCodes.put("AB",51);
		labels.put(51, new ArrayList<Label>());
		values.put(52,"British Columbia");
		shortCodes.put("BC",52);
		labels.put(52, new ArrayList<Label>());
		values.put(53,"Manitoba");
		shortCodes.put("MB",53);
		labels.put(53, new ArrayList<Label>());
		values.put(54,"New Brunswick");
		shortCodes.put("NB",54);
		labels.put(54, new ArrayList<Label>());
		values.put(55,"Newfoundland and Labrador");
		shortCodes.put("NL",55);
		labels.put(55, new ArrayList<Label>());
		values.put(56,"Nova Scotia");
		shortCodes.put("NS",56);
		labels.put(56, new ArrayList<Label>());
		values.put(57,"Nortwest Territories");
		shortCodes.put("NT",57);
		labels.put(57, new ArrayList<Label>());
		values.put(58,"Nunavut");
		shortCodes.put("NU",58);
		labels.put(58, new ArrayList<Label>());
		values.put(59,"Ontario");
		shortCodes.put("ON",59);
		labels.put(59, new ArrayList<Label>());
		values.put(60,"Prince Edward Island");
		shortCodes.put("PE",60);
		labels.put(60, new ArrayList<Label>());
		values.put(61,"Quebec");
		shortCodes.put("QC",61);
		labels.put(61, new ArrayList<Label>());
		values.put(62,"Saskatchewan");
		shortCodes.put("SK",62);
		labels.put(62, new ArrayList<Label>());
		values.put(63,"Yukon");
		shortCodes.put("YT",63);
		labels.put(63, new ArrayList<Label>());
		values.put(64,"Aguascalientes");
		shortCodes.put("AGU",64);
		labels.put(64, new ArrayList<Label>());
		values.put(65,"Baja California Norte");
		shortCodes.put("BCN",65);
		labels.put(65, new ArrayList<Label>());
		values.put(66,"Baja California Sur");
		shortCodes.put("BCS",66);
		labels.put(66, new ArrayList<Label>());
		values.put(67,"Campeche");
		shortCodes.put("CAM",67);
		labels.put(67, new ArrayList<Label>());
		values.put(68,"Chiapas");
		shortCodes.put("CHP",68);
		labels.put(68, new ArrayList<Label>());
		values.put(69,"Chihuahua");
		shortCodes.put("CHH",69);
		labels.put(69, new ArrayList<Label>());
		values.put(70,"Coahuila");
		shortCodes.put("COA",70);
		labels.put(70, new ArrayList<Label>());
		values.put(71,"Colima");
		shortCodes.put("COL",71);
		labels.put(71, new ArrayList<Label>());
		values.put(72,"Distrito Federal");
		shortCodes.put("CMX",72);
		labels.put(72, new ArrayList<Label>());
		values.put(73,"Durango");
		shortCodes.put("DUR",73);
		labels.put(73, new ArrayList<Label>());
		values.put(74,"Guanajuato");
		shortCodes.put("GUA",74);
		labels.put(74, new ArrayList<Label>());
		values.put(75,"Guerrero");
		shortCodes.put("GRO",75);
		labels.put(75, new ArrayList<Label>());
		values.put(76,"Hidalgo");
		shortCodes.put("HID",76);
		labels.put(76, new ArrayList<Label>());
		values.put(77,"Jalisco");
		shortCodes.put("JAL",77);
		labels.put(77, new ArrayList<Label>());
		values.put(78,"Mexico");
		shortCodes.put("MEX",78);
		labels.put(78, new ArrayList<Label>());
		values.put(79,"Michoacan");
		shortCodes.put("MIC",79);
		labels.put(79, new ArrayList<Label>());
		values.put(80,"Morelos");
		shortCodes.put("MOR",80);
		labels.put(80, new ArrayList<Label>());
		values.put(81,"Nayarit");
		shortCodes.put("NAY",81);
		labels.put(81, new ArrayList<Label>());
		values.put(82,"Nuevo Leon");
		shortCodes.put("NLE",82);
		labels.put(82, new ArrayList<Label>());
		values.put(83,"Oaxaca");
		shortCodes.put("OAX",83);
		labels.put(83, new ArrayList<Label>());
		values.put(84,"Puebla");
		shortCodes.put("PUE",84);
		labels.put(84, new ArrayList<Label>());
		values.put(85,"Queretaro");
		shortCodes.put("QUE",85);
		labels.put(85, new ArrayList<Label>());
		values.put(86,"Quintana Roo");
		shortCodes.put("ROO",86);
		labels.put(86, new ArrayList<Label>());
		values.put(87,"San Luis Potosi");
		shortCodes.put("SLP",87);
		labels.put(87, new ArrayList<Label>());
		values.put(88,"Sinaloa");
		shortCodes.put("SIN",88);
		labels.put(88, new ArrayList<Label>());
		values.put(89,"Sonora");
		shortCodes.put("SON",89);
		labels.put(89, new ArrayList<Label>());
		values.put(90,"Tabasco");
		shortCodes.put("TAB",90);
		labels.put(90, new ArrayList<Label>());
		values.put(91,"Tamaulipas");
		shortCodes.put("TAM",91);
		labels.put(91, new ArrayList<Label>());
		values.put(92,"Tiaxcala");
		shortCodes.put("TLA",92);
		labels.put(92, new ArrayList<Label>());
		values.put(93,"Veracruz");
		shortCodes.put("VER",93);
		labels.put(93, new ArrayList<Label>());
		values.put(94,"Yucatan");
		shortCodes.put("YUC",94);
		labels.put(94, new ArrayList<Label>());
		values.put(95,"Zacatecas");
		shortCodes.put("ZAC",95);
		labels.put(95, new ArrayList<Label>());
		values.put(96,"Washington DC");
		shortCodes.put("DC",96);
		labels.put(96, new ArrayList<Label>());
		values.put(97,"American Samoa");
		shortCodes.put("AS",97);
		labels.put(97, new ArrayList<Label>());
		values.put(98,"Federated States of Micronesia");
		shortCodes.put("FM",98);
		labels.put(98, new ArrayList<Label>());
		values.put(99,"Guam");
		shortCodes.put("GU",99);
		labels.put(99, new ArrayList<Label>());
		values.put(100,"Marshal Islands");
		shortCodes.put("MH",100);
		labels.put(100, new ArrayList<Label>());
		values.put(101,"Northern Mariana Islands");
		shortCodes.put("MP",101);
		labels.put(101, new ArrayList<Label>());
		values.put(102,"Palau");
		shortCodes.put("PW",102);
		labels.put(102, new ArrayList<Label>());
		values.put(103,"Puerto Rico");
		shortCodes.put("PR",103);
		labels.put(103, new ArrayList<Label>());
		values.put(104,"Virgin Islands");
		shortCodes.put("VI",104);
		labels.put(104, new ArrayList<Label>());
		values.put(105,"Labrador");
		shortCodes.put("LB",105);
		labels.put(105, new ArrayList<Label>());
		values.put(106,"Province du Quebec");
		shortCodes.put("PQ",106);
		labels.put(106, new ArrayList<Label>());
		values.put(108,"Armed Forces Americas");
		shortCodes.put("AA",108);
		labels.put(108, new ArrayList<Label>());
		values.put(109,"Armed Forces (Other;");
		shortCodes.put("AE",109);
		labels.put(109, new ArrayList<Label>());
		values.put(110,"Armed Forces Pacific");
		shortCodes.put("AP",110);
		labels.put(110, new ArrayList<Label>());
		values.put(111,"International");
		shortCodes.put("II",111);
		labels.put(111, new ArrayList<Label>());
		values.put(1000,"Department of Homeland Security");
		shortCodes.put("DHS",1000);
		labels.put(1000, new ArrayList<Label>());
		values.put(1001,"Federal or Military");
		shortCodes.put("FD",1001);
		labels.put(1001, new ArrayList<Label>());
		values.put(1002,"General Services Administration");
		shortCodes.put("GSA",1002);
		labels.put(1002, new ArrayList<Label>());
		values.put(1003,"Diplomat ");
		shortCodes.put("DL",1003);
		labels.put(1003, new ArrayList<Label>());
		values.put(1004,"Foreign Consul");
		shortCodes.put("FC",1004);
		labels.put(1004, new ArrayList<Label>());
		values.put(1005,"Puyallup");
		shortCodes.put("PUY",1005);
		labels.put(1005, new ArrayList<Label>());
		values.put(1006,"Colville");
		shortCodes.put("CLV",1006);
		labels.put(1006, new ArrayList<Label>());
		values.put(1007,"Lummi");
		shortCodes.put("LUM",1007);
		labels.put(1007, new ArrayList<Label>());
		values.put(1008,"Spokane Tribe");
		shortCodes.put("SPK",1008);
		labels.put(1008, new ArrayList<Label>());
		values.put(1009,"Quinault Indian Nation");
		shortCodes.put("QIN",1009);
		labels.put(1009, new ArrayList<Label>());
		values.put(1010,"Muckleshoot");
		shortCodes.put("MCK",1010);
		labels.put(1010, new ArrayList<Label>());
		values.put(1011,"Tulalip Tribes");
		shortCodes.put("TUL",1011);
		labels.put(1011, new ArrayList<Label>());
		values.put(1012,"Yakama Nation");
		shortCodes.put("YAK",1012);
		labels.put(1012, new ArrayList<Label>());
	}

	@Override
	public LinkedHashMap<Integer, String> getHashmap() {
		return values;
	}

	@Override
	public LinkedHashMap<String, Integer> getShortCodes() {
		return shortCodes;
	}
	@Override
	public LinkedHashMap<Integer, ArrayList<Label>> getLabels() {
		return labels;
	}
}