package com.jsantos.metadata.tolling;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import com.jsantos.orm.mt.MTEnumeration;
import com.jsantos.orm.label.Label;

public class EnuLicensePlateType extends MTEnumeration{
	static protected LinkedHashMap<Integer, String> values = new LinkedHashMap<>();
	static protected LinkedHashMap<String, Integer> shortCodes = new LinkedHashMap<>();
	static protected LinkedHashMap<Integer, ArrayList<Label>> labels = new LinkedHashMap<>();

	public static final int UNK = 0;
	public static final int AGRI = 1;
	public static final int AMBU = 2;
	public static final int AMOT = 3;
	public static final int ANTI = 4;
	public static final int APRO = 5;
	public static final int APTR = 6;
	public static final int HPASS = 8;
	public static final int CONEQ = 9;
	public static final int FARM = 11;
	public static final int FPOW = 12;
	public static final int APRO_DUP = 31;
	public static final int COMM = 32;
	public static final int CPASS = 33;
	public static final int DVETE = 34;
	public static final int HCAP = 35;
	public static final int IAPRO = 36;
	public static final int ICOMM = 37;
	public static final int ICPAS = 38;
	public static final int IDVET = 39;
	public static final int IHCAP = 40;
	public static final int IMOTO = 41;
	public static final int IPASS = 42;
	public static final int IVMOT = 43;
	public static final int IVVET = 44;
	public static final int MOTO = 45;
	public static final int PASS = 46;
	public static final int RADPL = 47;
	public static final int VMOTO = 49;
	public static final int VVETE = 50;
	public static final int ET_0061 = 61;
	public static final int ET_0062 = 62;
	public static final int ET_0063 = 63;
	public static final int ET_0064 = 64;
	public static final int ET_0065 = 65;
	public static final int ET_0066 = 66;
	public static final int ET_0067 = 67;
	public static final int ET_0069 = 69;
	public static final int ET_0071 = 71;
	public static final int ET_0072 = 72;
	public static final int ET_0073 = 73;
	public static final int ET_0074 = 74;
	public static final int ET_0075 = 75;
	public static final int ET_0076 = 76;
	public static final int ET_0078 = 78;
	public static final int ET_0080 = 80;
	public static final int ET_0081 = 81;
	public static final int ET_0082 = 82;
	public static final int ET_0083 = 83;
	public static final int ET_0084 = 84;
	public static final int ET_0085 = 85;
	public static final int ET_0086 = 86;
	public static final int ET_0087 = 87;
	public static final int ET_0088 = 88;
	public static final int ET_0089 = 89;
	public static final int ET_0090 = 90;
	public static final int ET_0091 = 91;
	public static final int ET_0092 = 92;
	public static final int ET_0093 = 93;
	public static final int AUTH = 97;
	public static final int BOATDEL = 100;
	public static final int BUS = 102;
	public static final int CAMP = 104;
	public static final int COMB = 107;
	public static final int CONSUL = 108;
	public static final int DEALER = 109;
	public static final int DEALVAN = 110;
	public static final int DELR = 111;
	public static final int FARMTRL = 113;
	public static final int HMOTO = 115;
	public static final int MVH = 128;
	public static final int MVT = 129;
	public static final int NDEAL = 130;
	public static final int NGNH = 131;
	public static final int NPURP = 132;
	public static final int OWNCONT = 134;
	public static final int PHMOT = 137;
	public static final int REP = 141;
	public static final int REPVAN = 142;
	public static final int SBUS = 143;
	public static final int SBUSP = 144;
	public static final int SPCPS = 149;
	public static final int SPPAS = 150;
	public static final int STAND = 151;
	public static final int TAXI = 157;
	public static final int TRAI = 158;
	public static final int TRCK = 159;
	public static final int TRNS = 160;
	public static final int VLRMOT = 161;
	public static final int ET_0163 = 163;
	public static final int ET_0164 = 164;
	public static final int ET_0165 = 165;
	public static final int ET_0166 = 166;
	public static final int ET_0167 = 167;
	public static final int ET_0168 = 168;
	public static final int ET_0169 = 169;
	public static final int ET_0170 = 170;
	public static final int ET_0171 = 171;
	public static final int ET_0172 = 172;
	public static final int ET_0173 = 173;
	public static final int ET_0174 = 174;
	public static final int ET_0175 = 175;
	public static final int ET_0176 = 176;
	public static final int ET_0177 = 177;
	public static final int ET_0178 = 178;
	public static final int ET_0179 = 179;
	public static final int ET_0180 = 180;
	public static final int ET_0181 = 181;
	public static final int ET_0182 = 182;
	public static final int ET_0183 = 183;
	public static final int ET_0184 = 184;
	public static final int ET_0185 = 185;
	public static final int ET_0186 = 186;
	public static final int ET_0187 = 187;
	public static final int ET_0188 = 188;
	public static final int ET_0189 = 189;
	public static final int ET_0190 = 190;
	public static final int ET_0191 = 191;
	public static final int ET_0192 = 192;
	public static final int ET_0193 = 193;
	public static final int ET_0194 = 194;
	public static final int ET_0195 = 195;
	public static final int ET_0196 = 196;
	public static final int ET_0197 = 197;
	public static final int ET_0198 = 198;
	public static final int ET_0199 = 199;
	public static final int ET_0200 = 200;
	public static final int ET_0201 = 201;
	public static final int ET_0202 = 202;
	public static final int ET_0203 = 203;
	public static final int ET_0204 = 204;
	public static final int ET_0205 = 205;
	public static final int ET_0206 = 206;
	public static final int ET_0207 = 207;
	public static final int ET_0208 = 208;
	public static final int ET_0209 = 209;
	public static final int ET_0210 = 210;
	public static final int ET_0211 = 211;
	public static final int ET_0212 = 212;
	public static final int ET_0213 = 213;
	public static final int ET_0214 = 214;
	public static final int ET_0215 = 215;
	public static final int ET_0216 = 216;
	public static final int ET_0217 = 217;
	public static final int ET_0218 = 218;
	public static final int ET_0219 = 219;
	public static final int ET_0220 = 220;
	public static final int ET_0221 = 221;
	public static final int ET_0222 = 222;
	public static final int ET_0223 = 223;
	public static final int ET_0224 = 224;
	public static final int ET_0225 = 225;
	public static final int ET_0226 = 226;
	public static final int ET_0227 = 227;
	public static final int ET_0228 = 228;
	public static final int ET_0229 = 229;
	public static final int ET_0230 = 230;
	public static final int ET_0231 = 231;
	public static final int ET_0232 = 232;
	public static final int ET_0233 = 233;
	public static final int ET_0234 = 234;
	public static final int ET_0235 = 235;
	public static final int ET_0236 = 236;
	public static final int ET_0237 = 237;
	public static final int ET_0238 = 238;
	public static final int ET_0239 = 239;
	public static final int ET_0240 = 240;
	public static final int ET_0241 = 241;
	public static final int ET_0242 = 242;
	public static final int ET_0243 = 243;
	public static final int ET_0244 = 244;
	public static final int ET_0245 = 245;
	public static final int ET_0246 = 246;
	public static final int ET_0247 = 247;
	public static final int ET_0248 = 248;
	public static final int ET_0249 = 249;
	public static final int ET_0250 = 250;
	public static final int ET_0251 = 251;
	public static final int ET_0252 = 252;
	public static final int ET_0253 = 253;
	public static final int ET_0254 = 254;
	public static final int ET_0255 = 255;
	public static final int ET_0256 = 256;
	public static final int ET_0257 = 257;
	public static final int ET_0258 = 258;
	public static final int ET_0259 = 259;
	public static final int ET_0260 = 260;
	public static final int ET_0261 = 261;
	public static final int ET_0262 = 262;
	public static final int ET_0263 = 263;
	public static final int ET_0264 = 264;
	public static final int ET_0265 = 265;
	public static final int ET_0266 = 266;
	public static final int ET_0267 = 267;
	public static final int ET_0268 = 268;
	public static final int ET_0269 = 269;
	public static final int ET_0270 = 270;
	public static final int ET_0271 = 271;
	public static final int ET_0272 = 272;
	public static final int ET_0273 = 273;
	public static final int ET_0274 = 274;
	public static final int ET_0275 = 275;
	public static final int ET_0276 = 276;
	public static final int ET_0277 = 277;
	public static final int ET_0278 = 278;
	public static final int ET_0279 = 279;
	public static final int ET_0280 = 280;
	public static final int TEMP = 281;
	public static final int NONSTD = 282;
	public static final int FOURH = 283;
	public static final int AF = 284;
	public static final int AR = 285;
	public static final int CG = 286;
	public static final int MC = 287;
	public static final int NG = 288;
	public static final int NA = 289;
	public static final int CV = 290;
	public static final int CVA = 291;
	public static final int CWU = 292;
	public static final int EWU = 293;
	public static final int GU = 294;
	public static final int SU = 295;
	public static final int GRN = 296;
	public static final int UW = 297;
	public static final int WSU = 298;
	public static final int WWU = 299;
	public static final int DP = 300;
	public static final int DPM = 301;
	public static final int EW = 302;
	public static final int D = 303;
	public static final int C = 304;
	public static final int K = 305;
	public static final int I = 306;
	public static final int M = 307;
	public static final int E = 308;
	public static final int SP = 309;
	public static final int WSP = 310;
	public static final int EX = 311;
	public static final int Q = 312;
	public static final int FO = 313;
	public static final int FPO = 314;
	public static final int HAM = 315;
	public static final int MM = 316;
	public static final int HCO = 317;
	public static final int KS = 318;
	public static final int LEM = 319;
	public static final int WW = 320;
	public static final int MU = 321;
	public static final int OFF = 322;
	public static final int PF = 323;
	public static final int RS = 324;
	public static final int SH = 325;
	public static final int FC = 326;
	public static final int BK = 327;
	public static final int SN = 328;
	public static final int S = 329;
	public static final int SD = 330;
	public static final int ST = 331;
	public static final int SF = 332;
	public static final int FFA = 333;
	public static final int FS = 334;
	public static final int LH = 335;
	public static final int NP = 336;
	public static final int PKR = 337;
	public static final int WR = 338;
	public static final int TN = 339;
	public static final int WB = 340;
	public static final int WD = 341;
	public static final int WE = 342;
	public static final int PT = 343;
	public static final int WWE = 344;
	public static final int AMR = 355;
	public static final int AVIA = 356;
	public static final int HORSELESS = 358;
	public static final int HORSELESS_M = 359;
	public static final int WA_STEELHEAD = 360;
	public static final int WA_FREDHUTCH = 361;
	public static final int WA_MARINERS = 362;
	public static final int WSUP = 363;
	public static final int WSUS = 364;
	public static final int GSA_G10 = 371;
	public static final int GSA_G11 = 372;
	public static final int GSA_G13 = 373;
	public static final int GSA_G14 = 374;
	public static final int GSA_G20 = 375;
	public static final int GSA_G31 = 376;
	public static final int GSA_G32 = 377;
	public static final int GSA_G41 = 378;
	public static final int GSA_G42 = 379;
	public static final int GSA_G43 = 380;
	public static final int GSA_G61 = 381;
	public static final int GSA_G62 = 382;
	public static final int GSA_G63 = 383;
	public static final int GSA_G71 = 384;
	public static final int GSA_G82 = 385;
	public static final int GSA_G87 = 386;
	public static final int GSA_G90 = 387;
	public static final int GSA_N58 = 388;

	static {
		values.put(0,"Unknown");
		shortCodes.put("UNK",0);
		labels.put(0, new ArrayList<Label>());
		values.put(1,"Agriculture");
		shortCodes.put("AGRI",1);
		labels.put(1, new ArrayList<Label>());
		values.put(2,"Ambulance");
		shortCodes.put("AMBU",2);
		labels.put(2, new ArrayList<Label>());
		values.put(3,"Antique Motorcycle");
		shortCodes.put("AMOT",3);
		labels.put(3, new ArrayList<Label>());
		values.put(4,"Antique");
		shortCodes.put("ANTI",4);
		labels.put(4, new ArrayList<Label>());
		values.put(5,"Apportioned Power Vehicle (Other3)");
		shortCodes.put("APRO",5);
		labels.put(5, new ArrayList<Label>());
		values.put(6,"Apportioned Trailer");
		shortCodes.put("APTR",6);
		labels.put(6, new ArrayList<Label>());
		values.put(8,"Conservation Moose");
		shortCodes.put("HPASS",8);
		labels.put(8, new ArrayList<Label>());
		values.put(9,"Construction Equipment");
		shortCodes.put("CONEQ",9);
		labels.put(9, new ArrayList<Label>());
		values.put(11,"Fam");
		shortCodes.put("FARM",11);
		labels.put(11, new ArrayList<Label>());
		values.put(12,"Former POW");
		shortCodes.put("FPOW",12);
		labels.put(12, new ArrayList<Label>());
		values.put(31,"Apportioned Power Vehicle (Other2)");
		shortCodes.put("APRO_DUP",31);
		labels.put(31, new ArrayList<Label>());
		values.put(32,"Commercial");
		shortCodes.put("COMM",32);
		labels.put(32, new ArrayList<Label>());
		values.put(33,"Moose Conservation Passenger");
		shortCodes.put("CPASS",33);
		labels.put(33, new ArrayList<Label>());
		values.put(34,"Disabled Veteran");
		shortCodes.put("DVETE",34);
		labels.put(34, new ArrayList<Label>());
		values.put(35,"Handicap");
		shortCodes.put("HCAP",35);
		labels.put(35, new ArrayList<Label>());
		values.put(36,"Initial Apportioned Vehicle");
		shortCodes.put("IAPRO",36);
		labels.put(36, new ArrayList<Label>());
		values.put(37,"Initial Commercial");
		shortCodes.put("ICOMM",37);
		labels.put(37, new ArrayList<Label>());
		values.put(38,"Initial Moose Conservation Passenger");
		shortCodes.put("ICPAS",38);
		labels.put(38, new ArrayList<Label>());
		values.put(39,"Initial Disabled Veteran");
		shortCodes.put("IDVET",39);
		labels.put(39, new ArrayList<Label>());
		values.put(40,"Initial Handicap");
		shortCodes.put("IHCAP",40);
		labels.put(40, new ArrayList<Label>());
		values.put(41,"Initial Motorcycle");
		shortCodes.put("IMOTO",41);
		labels.put(41, new ArrayList<Label>());
		values.put(42,"Initial Passenger");
		shortCodes.put("IPASS",42);
		labels.put(42, new ArrayList<Label>());
		values.put(43,"Initial Veteran Motorcycle");
		shortCodes.put("IVMOT",43);
		labels.put(43, new ArrayList<Label>());
		values.put(44,"Initial Regular Veteran");
		shortCodes.put("IVVET",44);
		labels.put(44, new ArrayList<Label>());
		values.put(45,"Motorcycle");
		shortCodes.put("MOTO",45);
		labels.put(45, new ArrayList<Label>());
		values.put(46,"Passenger");
		shortCodes.put("PASS",46);
		labels.put(46, new ArrayList<Label>());
		values.put(47,"Automobile Dealer (other)");
		shortCodes.put("RADPL",47);
		labels.put(47, new ArrayList<Label>());
		values.put(49,"Veteran Motorcycle");
		shortCodes.put("VMOTO",49);
		labels.put(49, new ArrayList<Label>());
		values.put(50,"Regular Veteran Plate");
		shortCodes.put("VVETE",50);
		labels.put(50, new ArrayList<Label>());
		values.put(61,"Ambulance/Emergency");
		shortCodes.put("ET_0061",61);
		labels.put(61, new ArrayList<Label>());
		values.put(62,"Authority Motorcycle (Other)");
		shortCodes.put("ET_0062",62);
		labels.put(62, new ArrayList<Label>());
		values.put(63,"Authority (Other)");
		shortCodes.put("ET_0063",63);
		labels.put(63, new ArrayList<Label>());
		values.put(64,"Bus (Other)");
		shortCodes.put("ET_0064",64);
		labels.put(64, new ArrayList<Label>());
		values.put(65,"Camper");
		shortCodes.put("ET_0065",65);
		labels.put(65, new ArrayList<Label>());
		values.put(66,"Livery");
		shortCodes.put("ET_0066",66);
		labels.put(66, new ArrayList<Label>());
		values.put(67,"Municipal Vehicle");
		shortCodes.put("ET_0067",67);
		labels.put(67, new ArrayList<Label>());
		values.put(69,"School Bus (Normal)");
		shortCodes.put("ET_0069",69);
		labels.put(69, new ArrayList<Label>());
		values.put(71,"Semi-Trailer");
		shortCodes.put("ET_0071",71);
		labels.put(71, new ArrayList<Label>());
		values.put(72,"State Motorcycle (Other)");
		shortCodes.put("ET_0072",72);
		labels.put(72, new ArrayList<Label>());
		values.put(73,"State Vehicle (Other3)");
		shortCodes.put("ET_0073",73);
		labels.put(73, new ArrayList<Label>());
		values.put(74,"Taxi (Other)");
		shortCodes.put("ET_0074",74);
		labels.put(74, new ArrayList<Label>());
		values.put(75,"Trailer (Other)");
		shortCodes.put("ET_0075",75);
		labels.put(75, new ArrayList<Label>());
		values.put(76,"Vanpool");
		shortCodes.put("ET_0076",76);
		labels.put(76, new ArrayList<Label>());
		values.put(78,"Combination (Other)");
		shortCodes.put("ET_0078",78);
		labels.put(78, new ArrayList<Label>());
		values.put(80,"Antique Auto");
		shortCodes.put("ET_0080",80);
		labels.put(80, new ArrayList<Label>());
		values.put(81,"Black Bear Specialty Plate");
		shortCodes.put("ET_0081",81);
		labels.put(81, new ArrayList<Label>());
		values.put(82,"Conservation Commercial");
		shortCodes.put("ET_0082",82);
		labels.put(82, new ArrayList<Label>());
		values.put(83,"Conservation Disability");
		shortCodes.put("ET_0083",83);
		labels.put(83, new ArrayList<Label>());
		values.put(84,"Conservation Passenger");
		shortCodes.put("ET_0084",84);
		labels.put(84, new ArrayList<Label>());
		values.put(85,"Disability Special Veteran Plate");
		shortCodes.put("ET_0085",85);
		labels.put(85, new ArrayList<Label>());
		values.put(86,"Fire Fighter");
		shortCodes.put("ET_0086",86);
		labels.put(86, new ArrayList<Label>());
		values.put(87,"Lobster Specialty Plate");
		shortCodes.put("ET_0087",87);
		labels.put(87, new ArrayList<Label>());
		values.put(88,"Purple Heart");
		shortCodes.put("ET_0088",88);
		labels.put(88, new ArrayList<Label>());
		values.put(89,"Purple Heart Motorcycle");
		shortCodes.put("ET_0089",89);
		labels.put(89, new ArrayList<Label>());
		values.put(90,"Conservation Motor home");
		shortCodes.put("ET_0090",90);
		labels.put(90, new ArrayList<Label>());
		values.put(91,"Univ. of Maine System");
		shortCodes.put("ET_0091",91);
		labels.put(91, new ArrayList<Label>());
		values.put(92,"Wabanaki");
		shortCodes.put("ET_0092",92);
		labels.put(92, new ArrayList<Label>());
		values.put(93,"Disability Motor home");
		shortCodes.put("ET_0093",93);
		labels.put(93, new ArrayList<Label>());
		values.put(97,"Authority");
		shortCodes.put("AUTH",97);
		labels.put(97, new ArrayList<Label>());
		values.put(100,"Boat Dealer");
		shortCodes.put("BOATDEL",100);
		labels.put(100, new ArrayList<Label>());
		values.put(102,"Bus");
		shortCodes.put("BUS",102);
		labels.put(102, new ArrayList<Label>());
		values.put(104,"Camper Trailer");
		shortCodes.put("CAMP",104);
		labels.put(104, new ArrayList<Label>());
		values.put(107,"Combination");
		shortCodes.put("COMB",107);
		labels.put(107, new ArrayList<Label>());
		values.put(108,"Consulate General");
		shortCodes.put("CONSUL",108);
		labels.put(108, new ArrayList<Label>());
		values.put(109,"Dealer (other)");
		shortCodes.put("DEALER",109);
		labels.put(109, new ArrayList<Label>());
		values.put(110,"Dealer Vanity");
		shortCodes.put("DEALVAN",110);
		labels.put(110, new ArrayList<Label>());
		values.put(111,"Dealer");
		shortCodes.put("DELR",111);
		labels.put(111, new ArrayList<Label>());
		values.put(113,"Farm Trailer");
		shortCodes.put("FARMTRL",113);
		labels.put(113, new ArrayList<Label>());
		values.put(115,"Handicapped Motorcycle");
		shortCodes.put("HMOTO",115);
		labels.put(115, new ArrayList<Label>());
		values.put(128,"Municipal Vehicle (Other)");
		shortCodes.put("MVH",128);
		labels.put(128, new ArrayList<Label>());
		values.put(129,"Municipal Motorcycle (Other)");
		shortCodes.put("MVT",129);
		labels.put(129, new ArrayList<Label>());
		values.put(130,"New And Used Dealer");
		shortCodes.put("NDEAL",130);
		labels.put(130, new ArrayList<Label>());
		values.put(131,"Nation Guard");
		shortCodes.put("NGNH",131);
		labels.put(131, new ArrayList<Label>());
		values.put(132,"Purple-Heart");
		shortCodes.put("NPURP",132);
		labels.put(132, new ArrayList<Label>());
		values.put(134,"Owner Contractor");
		shortCodes.put("OWNCONT",134);
		labels.put(134, new ArrayList<Label>());
		values.put(137,"Purple Heart Motorcycle");
		shortCodes.put("PHMOT",137);
		labels.put(137, new ArrayList<Label>());
		values.put(141,"Repair");
		shortCodes.put("REP",141);
		labels.put(141, new ArrayList<Label>());
		values.put(142,"Repair Vanity");
		shortCodes.put("REPVAN",142);
		labels.put(142, new ArrayList<Label>());
		values.put(143,"School Normal");
		shortCodes.put("SBUS",143);
		labels.put(143, new ArrayList<Label>());
		values.put(144,"School Pupil");
		shortCodes.put("SBUSP",144);
		labels.put(144, new ArrayList<Label>());
		values.put(149,"Moose Conservation Passenger");
		shortCodes.put("SPCPS",149);
		labels.put(149, new ArrayList<Label>());
		values.put(150,"Initial Moose Conservation Passenger (Other)");
		shortCodes.put("SPPAS",150);
		labels.put(150, new ArrayList<Label>());
		values.put(151,"Standard");
		shortCodes.put("STAND",151);
		labels.put(151, new ArrayList<Label>());
		values.put(157,"Taxi");
		shortCodes.put("TAXI",157);
		labels.put(157, new ArrayList<Label>());
		values.put(158,"Trailer");
		shortCodes.put("TRAI",158);
		labels.put(158, new ArrayList<Label>());
		values.put(159,"Truck");
		shortCodes.put("TRCK",159);
		labels.put(159, new ArrayList<Label>());
		values.put(160,"Transporter");
		shortCodes.put("TRNS",160);
		labels.put(160, new ArrayList<Label>());
		values.put(161,"Legion of Valor Motorcycle");
		shortCodes.put("VLRMOT",161);
		labels.put(161, new ArrayList<Label>());
		values.put(163,"Hearse");
		shortCodes.put("ET_0163",163);
		labels.put(163, new ArrayList<Label>());
		values.put(164,"Antique Vanity");
		shortCodes.put("ET_0164",164);
		labels.put(164, new ArrayList<Label>());
		values.put(165,"Former Pow Vanity");
		shortCodes.put("ET_0165",165);
		labels.put(165, new ArrayList<Label>());
		values.put(166,"Handicapped Motorcycle Vanity");
		shortCodes.put("ET_0166",166);
		labels.put(166, new ArrayList<Label>());
		values.put(167,"National Guard Vanity");
		shortCodes.put("ET_0167",167);
		labels.put(167, new ArrayList<Label>());
		values.put(168,"Purple Hearth Vanity");
		shortCodes.put("ET_0168",168);
		labels.put(168, new ArrayList<Label>());
		values.put(169,"Motorcycle Purple Hearth Vanity");
		shortCodes.put("ET_0169",169);
		labels.put(169, new ArrayList<Label>());
		values.put(170,"Moose Park Vanity");
		shortCodes.put("ET_0170",170);
		labels.put(170, new ArrayList<Label>());
		values.put(171,"State Park Vanity");
		shortCodes.put("ET_0171",171);
		labels.put(171, new ArrayList<Label>());
		values.put(172,"Street Road Vanity");
		shortCodes.put("ET_0172",172);
		labels.put(172, new ArrayList<Label>());
		values.put(173,"Trailer Vanity");
		shortCodes.put("ET_0173",173);
		labels.put(173, new ArrayList<Label>());
		values.put(174,"National Guard");
		shortCodes.put("ET_0174",174);
		labels.put(174, new ArrayList<Label>());
		values.put(175,"Pearl Harbor Survivor Vanity");
		shortCodes.put("ET_0175",175);
		labels.put(175, new ArrayList<Label>());
		values.put(176,"Permanent State");
		shortCodes.put("ET_0176",176);
		labels.put(176, new ArrayList<Label>());
		values.put(177,"Permanent City Town");
		shortCodes.put("ET_0177",177);
		labels.put(177, new ArrayList<Label>());
		values.put(178,"Pearl Harbor Survivor");
		shortCodes.put("ET_0178",178);
		labels.put(178, new ArrayList<Label>());
		values.put(179,"Commercial Special");
		shortCodes.put("ET_0179",179);
		labels.put(179, new ArrayList<Label>());
		values.put(180,"Street Rod");
		shortCodes.put("ET_0180",180);
		labels.put(180, new ArrayList<Label>());
		values.put(181,"Passenger Reserved");
		shortCodes.put("ET_0181",181);
		labels.put(181, new ArrayList<Label>());
		values.put(182,"Passenger Special");
		shortCodes.put("ET_0182",182);
		labels.put(182, new ArrayList<Label>());
		values.put(183,"Passenger Year of Manufacture");
		shortCodes.put("ET_0183",183);
		labels.put(183, new ArrayList<Label>());
		values.put(184,"Commercial Reserved");
		shortCodes.put("ET_0184",184);
		labels.put(184, new ArrayList<Label>());
		values.put(185,"Taxi Reserved");
		shortCodes.put("ET_0185",185);
		labels.put(185, new ArrayList<Label>());
		values.put(186,"Trailer Reserved");
		shortCodes.put("ET_0186",186);
		labels.put(186, new ArrayList<Label>());
		values.put(187,"Semi Trailer Reserved");
		shortCodes.put("ET_0187",187);
		labels.put(187, new ArrayList<Label>());
		values.put(188,"Motorcycle Reserved");
		shortCodes.put("ET_0188",188);
		labels.put(188, new ArrayList<Label>());
		values.put(189,"Motorcycle Special");
		shortCodes.put("ET_0189",189);
		labels.put(189, new ArrayList<Label>());
		values.put(190,"Motorcycle Dealer (Other)");
		shortCodes.put("ET_0190",190);
		labels.put(190, new ArrayList<Label>());
		values.put(191,"Ambulance Reserved");
		shortCodes.put("ET_0191",191);
		labels.put(191, new ArrayList<Label>());
		values.put(192,"Camper Reserved");
		shortCodes.put("ET_0192",192);
		labels.put(192, new ArrayList<Label>());
		values.put(193,"Camper Vanity");
		shortCodes.put("ET_0193",193);
		labels.put(193, new ArrayList<Label>());
		values.put(194,"Bus Reserved");
		shortCodes.put("ET_0194",194);
		labels.put(194, new ArrayList<Label>());
		values.put(195,"Bus Vanity");
		shortCodes.put("ET_0195",195);
		labels.put(195, new ArrayList<Label>());
		values.put(196,"School Bus Reserved");
		shortCodes.put("ET_0196",196);
		labels.put(196, new ArrayList<Label>());
		values.put(197,"Livery Reserved");
		shortCodes.put("ET_0197",197);
		labels.put(197, new ArrayList<Label>());
		values.put(198,"Livery Vanity");
		shortCodes.put("ET_0198",198);
		labels.put(198, new ArrayList<Label>());
		values.put(199,"Agriculture Commercial");
		shortCodes.put("ET_0199",199);
		labels.put(199, new ArrayList<Label>());
		values.put(200,"Agriculture Farm Vehicle");
		shortCodes.put("ET_0200",200);
		labels.put(200, new ArrayList<Label>());
		values.put(201,"Agriculture Passenger");
		shortCodes.put("ET_0201",201);
		labels.put(201, new ArrayList<Label>());
		values.put(202,"Animal Welfare");
		shortCodes.put("ET_0202",202);
		labels.put(202, new ArrayList<Label>());
		values.put(203,"Breast Cancer Support");
		shortCodes.put("ET_0203",203);
		labels.put(203, new ArrayList<Label>());
		values.put(204,"Conservation Trailer");
		shortCodes.put("ET_0204",204);
		labels.put(204, new ArrayList<Label>());
		values.put(205,"County Sheriff");
		shortCodes.put("ET_0205",205);
		labels.put(205, new ArrayList<Label>());
		values.put(206,"Custom Vehicle");
		shortCodes.put("ET_0206",206);
		labels.put(206, new ArrayList<Label>());
		values.put(207,"Disability Special Veteran");
		shortCodes.put("ET_0207",207);
		labels.put(207, new ArrayList<Label>());
		values.put(208,"Gold Star");
		shortCodes.put("ET_0208",208);
		labels.put(208, new ArrayList<Label>());
		values.put(209,"Lobster Commercial");
		shortCodes.put("ET_0209",209);
		labels.put(209, new ArrayList<Label>());
		values.put(210,"Low Speed Vehicle");
		shortCodes.put("ET_0210",210);
		labels.put(210, new ArrayList<Label>());
		values.put(211,"Motor Home");
		shortCodes.put("ET_0211",211);
		labels.put(211, new ArrayList<Label>());
		values.put(212,"Medal of Honor");
		shortCodes.put("ET_0212",212);
		labels.put(212, new ArrayList<Label>());
		values.put(213,"Special Equipment");
		shortCodes.put("ET_0213",213);
		labels.put(213, new ArrayList<Label>());
		values.put(214,"Sportsman");
		shortCodes.put("ET_0214",214);
		labels.put(214, new ArrayList<Label>());
		values.put(215,"Tractor");
		shortCodes.put("ET_0215",215);
		labels.put(215, new ArrayList<Label>());
		values.put(216,"Support Troops");
		shortCodes.put("ET_0216",216);
		labels.put(216, new ArrayList<Label>());
		values.put(217,"Commercial Tractor");
		shortCodes.put("ET_0217",217);
		labels.put(217, new ArrayList<Label>());
		values.put(218,"Motorcycle Disabled Veteran");
		shortCodes.put("ET_0218",218);
		labels.put(218, new ArrayList<Label>());
		values.put(219,"Camp Trailer");
		shortCodes.put("ET_0219",219);
		labels.put(219, new ArrayList<Label>());
		values.put(220,"High Millage Vehicle");
		shortCodes.put("ET_0220",220);
		labels.put(220, new ArrayList<Label>());
		values.put(221,"Factory");
		shortCodes.put("ET_0221",221);
		labels.put(221, new ArrayList<Label>());
		values.put(222,"Classic Vehicle");
		shortCodes.put("ET_0222",222);
		labels.put(222, new ArrayList<Label>());
		values.put(223,"General District Bus");
		shortCodes.put("ET_0223",223);
		labels.put(223, new ArrayList<Label>());
		values.put(224,"US Senate/Congress");
		shortCodes.put("ET_0224",224);
		labels.put(224, new ArrayList<Label>());
		values.put(225,"Volunteer Firefighter");
		shortCodes.put("ET_0225",225);
		labels.put(225, new ArrayList<Label>());
		values.put(226,"State Service Bus");
		shortCodes.put("ET_0226",226);
		labels.put(226, new ArrayList<Label>());
		values.put(227,"School Bus Livery");
		shortCodes.put("ET_0227",227);
		labels.put(227, new ArrayList<Label>());
		values.put(228,"Wrecker");
		shortCodes.put("ET_0228",228);
		labels.put(228, new ArrayList<Label>());
		values.put(229,"US Military/Services/Protect");
		shortCodes.put("ET_0229",229);
		labels.put(229, new ArrayList<Label>());
		values.put(230,"Vanity Sports");
		shortCodes.put("ET_0230",230);
		labels.put(230, new ArrayList<Label>());
		values.put(231,"Wold University Games");
		shortCodes.put("ET_0231",231);
		labels.put(231, new ArrayList<Label>());
		values.put(232,"Jewish War Veterans of America");
		shortCodes.put("ET_0232",232);
		labels.put(232, new ArrayList<Label>());
		values.put(233,"Marine Corps League");
		shortCodes.put("ET_0233",233);
		labels.put(233, new ArrayList<Label>());
		values.put(234,"County Legislators");
		shortCodes.put("ET_0234",234);
		labels.put(234, new ArrayList<Label>());
		values.put(235,"Board of Supervisors");
		shortCodes.put("ET_0235",235);
		labels.put(235, new ArrayList<Label>());
		values.put(236,"Vanity");
		shortCodes.put("ET_0236",236);
		labels.put(236, new ArrayList<Label>());
		values.put(237,"Court");
		shortCodes.put("ET_0237",237);
		labels.put(237, new ArrayList<Label>());
		values.put(238,"NY Assembly");
		shortCodes.put("ET_0238",238);
		labels.put(238, new ArrayList<Label>());
		values.put(239,"US Congress");
		shortCodes.put("ET_0239",239);
		labels.put(239, new ArrayList<Label>());
		values.put(240,"US Senate");
		shortCodes.put("ET_0240",240);
		labels.put(240, new ArrayList<Label>());
		values.put(241,"Hearse Special Registration");
		shortCodes.put("ET_0241",241);
		labels.put(241, new ArrayList<Label>());
		values.put(242,"Court of Appeals");
		shortCodes.put("ET_0242",242);
		labels.put(242, new ArrayList<Label>());
		values.put(243,"Commercial Special Purpose");
		shortCodes.put("ET_0243",243);
		labels.put(243, new ArrayList<Label>());
		values.put(244,"NY Council");
		shortCodes.put("ET_0244",244);
		labels.put(244, new ArrayList<Label>());
		values.put(245,"Appellate Term");
		shortCodes.put("ET_0245",245);
		labels.put(245, new ArrayList<Label>());
		values.put(246,"Physician");
		shortCodes.put("ET_0246",246);
		labels.put(246, new ArrayList<Label>());
		values.put(247,"Court of Claims");
		shortCodes.put("ET_0247",247);
		labels.put(247, new ArrayList<Label>());
		values.put(248,"Congressional Medal of Honor");
		shortCodes.put("ET_0248",248);
		labels.put(248, new ArrayList<Label>());
		values.put(249,"Supreme Court");
		shortCodes.put("ET_0249",249);
		labels.put(249, new ArrayList<Label>());
		values.put(250,"County Clerk");
		shortCodes.put("ET_0250",250);
		labels.put(250, new ArrayList<Label>());
		values.put(251,"Air National Guard");
		shortCodes.put("ET_0251",251);
		labels.put(251, new ArrayList<Label>());
		values.put(252,"Army National Guard");
		shortCodes.put("ET_0252",252);
		labels.put(252, new ArrayList<Label>());
		values.put(253,"Naval Militia");
		shortCodes.put("ET_0253",253);
		labels.put(253, new ArrayList<Label>());
		values.put(254,"State National Guard");
		shortCodes.put("ET_0254",254);
		labels.put(254, new ArrayList<Label>());
		values.put(255,"Ham Radio Operator");
		shortCodes.put("ET_0255",255);
		labels.put(255, new ArrayList<Label>());
		values.put(256,"Birthplace of Baseball");
		shortCodes.put("ET_0256",256);
		labels.put(256, new ArrayList<Label>());
		values.put(257,"Volunteer Ambulance");
		shortCodes.put("ET_0257",257);
		labels.put(257, new ArrayList<Label>());
		values.put(258,"Survivors of the Shield");
		shortCodes.put("ET_0258",258);
		labels.put(258, new ArrayList<Label>());
		values.put(259,"Transporter (Other)");
		shortCodes.put("ET_0259",259);
		labels.put(259, new ArrayList<Label>());
		values.put(260,"Counties and Regions");
		shortCodes.put("ET_0260",260);
		labels.put(260, new ArrayList<Label>());
		values.put(261,"Commercial Sports");
		shortCodes.put("ET_0261",261);
		labels.put(261, new ArrayList<Label>());
		values.put(262,"State Official");
		shortCodes.put("ET_0262",262);
		labels.put(262, new ArrayList<Label>());
		values.put(263,"Motorcycle Organizational");
		shortCodes.put("ET_0263",263);
		labels.put(263, new ArrayList<Label>());
		values.put(264,"Trailer Light");
		shortCodes.put("ET_0264",264);
		labels.put(264, new ArrayList<Label>());
		values.put(265,"Trailer Commercial Semi");
		shortCodes.put("ET_0265",265);
		labels.put(265, new ArrayList<Label>());
		values.put(266,"EM - Political Subdivision");
		shortCodes.put("ET_0266",266);
		labels.put(266, new ArrayList<Label>());
		values.put(267,"Public Service");
		shortCodes.put("ET_0267",267);
		labels.put(267, new ArrayList<Label>());
		values.put(268,"Suburban");
		shortCodes.put("ET_0268",268);
		labels.put(268, new ArrayList<Label>());
		values.put(269,"Jitney");
		shortCodes.put("ET_0269",269);
		labels.put(269, new ArrayList<Label>());
		values.put(270,"State");
		shortCodes.put("ET_0270",270);
		labels.put(270, new ArrayList<Label>());
		values.put(271,"City");
		shortCodes.put("ET_0271",271);
		labels.put(271, new ArrayList<Label>());
		values.put(272,"Town");
		shortCodes.put("ET_0272",272);
		labels.put(272, new ArrayList<Label>());
		values.put(273,"Police");
		shortCodes.put("ET_0273",273);
		labels.put(273, new ArrayList<Label>());
		values.put(274,"State Police");
		shortCodes.put("ET_0274",274);
		labels.put(274, new ArrayList<Label>());
		values.put(275,"House");
		shortCodes.put("ET_0275",275);
		labels.put(275, new ArrayList<Label>());
		values.put(276,"Used Car Dealer");
		shortCodes.put("ET_0276",276);
		labels.put(276, new ArrayList<Label>());
		values.put(277,"In-Transit");
		shortCodes.put("ET_0277",277);
		labels.put(277, new ArrayList<Label>());
		values.put(278,"Bailee");
		shortCodes.put("ET_0278",278);
		labels.put(278, new ArrayList<Label>());
		values.put(279,"Racer Tow");
		shortCodes.put("ET_0279",279);
		labels.put(279, new ArrayList<Label>());
		values.put(280,"40 & 8");
		shortCodes.put("ET_0280",280);
		labels.put(280, new ArrayList<Label>());
		values.put(281,"Temporary");
		shortCodes.put("TEMP",281);
		labels.put(281, new ArrayList<Label>());
		values.put(282,"Non-Standard");
		shortCodes.put("NONSTD",282);
		labels.put(282, new ArrayList<Label>());
		values.put(283,"4-H");
		shortCodes.put("FOURH",283);
		labels.put(283, new ArrayList<Label>());
		values.put(284,"Armed Forces-Air Force");
		shortCodes.put("AF",284);
		labels.put(284, new ArrayList<Label>());
		values.put(285,"Armed Forces-Army");
		shortCodes.put("AR",285);
		labels.put(285, new ArrayList<Label>());
		values.put(286,"Armed Forces-Coast Guard");
		shortCodes.put("CG",286);
		labels.put(286, new ArrayList<Label>());
		values.put(287,"Armed Forces-Marine Corps");
		shortCodes.put("MC",287);
		labels.put(287, new ArrayList<Label>());
		values.put(288,"Armed Forces-National Guard");
		shortCodes.put("NG",288);
		labels.put(288, new ArrayList<Label>());
		values.put(289,"Armed Forces-Navy");
		shortCodes.put("NA",289);
		labels.put(289, new ArrayList<Label>());
		values.put(290,"Collector Vehicle");
		shortCodes.put("CV",290);
		labels.put(290, new ArrayList<Label>());
		values.put(291,"Collector Vehicle Motorcycle");
		shortCodes.put("CVA",291);
		labels.put(291, new ArrayList<Label>());
		values.put(292,"Collegiate-Central WA Univ Wildcat");
		shortCodes.put("CWU",292);
		labels.put(292, new ArrayList<Label>());
		values.put(293,"Collegiate-Eastern WA Univ Eagle");
		shortCodes.put("EWU",293);
		labels.put(293, new ArrayList<Label>());
		values.put(294,"Collegiate-Gonzaga Univ Bulldog");
		shortCodes.put("GU",294);
		labels.put(294, new ArrayList<Label>());
		values.put(295,"Collegiate-Seattle Univ Redhawk");
		shortCodes.put("SU",295);
		labels.put(295, new ArrayList<Label>());
		values.put(296,"Collegiate-The Evergreen State College Tree");
		shortCodes.put("GRN",296);
		labels.put(296, new ArrayList<Label>());
		values.put(297,"Collegiate-University of Washington Husky");
		shortCodes.put("UW",297);
		labels.put(297, new ArrayList<Label>());
		values.put(298,"Collegiate-WA State Univ Cougar");
		shortCodes.put("WSU",298);
		labels.put(298, new ArrayList<Label>());
		values.put(299,"Collegiate-Western WA Univ Viking");
		shortCodes.put("WWU",299);
		labels.put(299, new ArrayList<Label>());
		values.put(300,"Disabled Parking");
		shortCodes.put("DP",300);
		labels.put(300, new ArrayList<Label>());
		values.put(301,"Disabled Parking Motorcycle");
		shortCodes.put("DPM",301);
		labels.put(301, new ArrayList<Label>());
		values.put(302,"Endangered Wildlife Orca");
		shortCodes.put("EW",302);
		labels.put(302, new ArrayList<Label>());
		values.put(303,"Exempt/city");
		shortCodes.put("D",303);
		labels.put(303, new ArrayList<Label>());
		values.put(304,"Exempt/county");
		shortCodes.put("C",304);
		labels.put(304, new ArrayList<Label>());
		values.put(305,"Exempt/DOT");
		shortCodes.put("K",305);
		labels.put(305, new ArrayList<Label>());
		values.put(306,"Exempt Indian");
		shortCodes.put("I",306);
		labels.put(306, new ArrayList<Label>());
		values.put(307,"Exempt motor pool");
		shortCodes.put("M",307);
		labels.put(307, new ArrayList<Label>());
		values.put(308,"Exempt/state");
		shortCodes.put("E",308);
		labels.put(308, new ArrayList<Label>());
		values.put(309,"Exempt/WSP");
		shortCodes.put("SP",309);
		labels.put(309, new ArrayList<Label>());
		values.put(310,"Exempt/WSP patrol cars");
		shortCodes.put("WSP",310);
		labels.put(310, new ArrayList<Label>());
		values.put(311,"Exempt Motorcycle");
		shortCodes.put("EX",311);
		labels.put(311, new ArrayList<Label>());
		values.put(312,"Farm Exempt Decals");
		shortCodes.put("Q",312);
		labels.put(312, new ArrayList<Label>());
		values.put(313,"Foreign Organization");
		shortCodes.put("FO",313);
		labels.put(313, new ArrayList<Label>());
		values.put(314,"Former Prisoner Of War");
		shortCodes.put("FPO",314);
		labels.put(314, new ArrayList<Label>());
		values.put(315,"HAM/MARS");
		shortCodes.put("HAM",315);
		labels.put(315, new ArrayList<Label>());
		values.put(316,"Helping Kids Speak");
		shortCodes.put("MM",316);
		labels.put(316, new ArrayList<Label>());
		values.put(317,"Honorary Consular");
		shortCodes.put("HCO",317);
		labels.put(317, new ArrayList<Label>());
		values.put(318,"Keep Kids Safe");
		shortCodes.put("KS",318);
		labels.put(318, new ArrayList<Label>());
		values.put(319,"Law Enforcement Memorial");
		shortCodes.put("LEM",319);
		labels.put(319, new ArrayList<Label>());
		values.put(320,"Motorcycle Trailer");
		shortCodes.put("WW",320);
		labels.put(320, new ArrayList<Label>());
		values.put(321,"Music Matters");
		shortCodes.put("MU",321);
		labels.put(321, new ArrayList<Label>());
		values.put(322,"Off Road Decal");
		shortCodes.put("OFF",322);
		labels.put(322, new ArrayList<Label>());
		values.put(323,"Professional Firefighter");
		shortCodes.put("PF",323);
		labels.put(323, new ArrayList<Label>());
		values.put(324,"Rideshare");
		shortCodes.put("RS",324);
		labels.put(324, new ArrayList<Label>());
		values.put(325,"Seattle Seahawks");
		shortCodes.put("SH",325);
		labels.put(325, new ArrayList<Label>());
		values.put(326,"Seattle Sounders FC");
		shortCodes.put("FC",326);
		labels.put(326, new ArrayList<Label>());
		values.put(327,"Share the Road");
		shortCodes.put("BK",327);
		labels.put(327, new ArrayList<Label>());
		values.put(328,"Ski & Ride");
		shortCodes.put("SN",328);
		labels.put(328, new ArrayList<Label>());
		values.put(329,"Snowmobile Decals");
		shortCodes.put("S",329);
		labels.put(329, new ArrayList<Label>());
		values.put(330,"Square Dancer");
		shortCodes.put("SD",330);
		labels.put(330, new ArrayList<Label>());
		values.put(331,"Stadium Mariners");
		shortCodes.put("ST",331);
		labels.put(331, new ArrayList<Label>());
		values.put(332,"State Flower");
		shortCodes.put("SF",332);
		labels.put(332, new ArrayList<Label>());
		values.put(333,"Washington Farmers and Ranchers");
		shortCodes.put("FFA",333);
		labels.put(333, new ArrayList<Label>());
		values.put(334,"Washington Fish");
		shortCodes.put("FS",334);
		labels.put(334, new ArrayList<Label>());
		values.put(335,"Washington Lighthouses");
		shortCodes.put("LH",335);
		labels.put(335, new ArrayList<Label>());
		values.put(336,"Washington National Parks Fund");
		shortCodes.put("NP",336);
		labels.put(336, new ArrayList<Label>());
		values.put(337,"Washington Parks & Recreation");
		shortCodes.put("PKR",337);
		labels.put(337, new ArrayList<Label>());
		values.put(338,"Washington State Wrestling");
		shortCodes.put("WR",338);
		labels.put(338, new ArrayList<Label>());
		values.put(339,"Washington Tennis");
		shortCodes.put("TN",339);
		labels.put(339, new ArrayList<Label>());
		values.put(340,"Washington Wildlife-Bear");
		shortCodes.put("WB",340);
		labels.put(340, new ArrayList<Label>());
		values.put(341,"Washington Wildlife-Deer");
		shortCodes.put("WD",341);
		labels.put(341, new ArrayList<Label>());
		values.put(342,"Washington Wildlife-Elk");
		shortCodes.put("WE",342);
		labels.put(342, new ArrayList<Label>());
		values.put(343,"We Love Our Pets");
		shortCodes.put("PT",343);
		labels.put(343, new ArrayList<Label>());
		values.put(344,"Wild on Washington Eagle");
		shortCodes.put("WWE",344);
		labels.put(344, new ArrayList<Label>());
		values.put(355,"Amateur Radio Operator");
		shortCodes.put("AMR",355);
		labels.put(355, new ArrayList<Label>());
		values.put(356,"Aviation");
		shortCodes.put("AVIA",356);
		labels.put(356, new ArrayList<Label>());
		values.put(358,"Horseless Carriage");
		shortCodes.put("HORSELESS",358);
		labels.put(358, new ArrayList<Label>());
		values.put(359,"Horseless Carriage Motocycle");
		shortCodes.put("HORSELESS_M",359);
		labels.put(359, new ArrayList<Label>());
		values.put(360,"Washington Steelhead");
		shortCodes.put("WA_STEELHEAD",360);
		labels.put(360, new ArrayList<Label>());
		values.put(361,"Fred Hutchinson Cancer Research");
		shortCodes.put("WA_FREDHUTCH",361);
		labels.put(361, new ArrayList<Label>());
		values.put(362,"Washington Mariniers");
		shortCodes.put("WA_MARINERS",362);
		labels.put(362, new ArrayList<Label>());
		values.put(363,"Collegiate-WA State Univ Cougar -- prefix (deprecated)");
		shortCodes.put("WSUP",363);
		labels.put(363, new ArrayList<Label>());
		values.put(364,"Collegiate-WA State Univ Cougar-- suffix (deprecated) ");
		shortCodes.put("WSUS",364);
		labels.put(364, new ArrayList<Label>());
		values.put(371,"Goods Services Administration-G10");
		shortCodes.put("GSA_G10",371);
		labels.put(371, new ArrayList<Label>());
		values.put(372,"Goods Services Administration-G11");
		shortCodes.put("GSA_G11",372);
		labels.put(372, new ArrayList<Label>());
		values.put(373,"Goods Services Administration-G13");
		shortCodes.put("GSA_G13",373);
		labels.put(373, new ArrayList<Label>());
		values.put(374,"Goods Services Administration-G14");
		shortCodes.put("GSA_G14",374);
		labels.put(374, new ArrayList<Label>());
		values.put(375,"Goods Services Administration-G20");
		shortCodes.put("GSA_G20",375);
		labels.put(375, new ArrayList<Label>());
		values.put(376,"Goods Services Administration-G31");
		shortCodes.put("GSA_G31",376);
		labels.put(376, new ArrayList<Label>());
		values.put(377,"Goods Services Administration-G32");
		shortCodes.put("GSA_G32",377);
		labels.put(377, new ArrayList<Label>());
		values.put(378,"Goods Services Administration-G41");
		shortCodes.put("GSA_G41",378);
		labels.put(378, new ArrayList<Label>());
		values.put(379,"Goods Services Administration-G42");
		shortCodes.put("GSA_G42",379);
		labels.put(379, new ArrayList<Label>());
		values.put(380,"Goods Services Administration-G43");
		shortCodes.put("GSA_G43",380);
		labels.put(380, new ArrayList<Label>());
		values.put(381,"Goods Services Administration-G61");
		shortCodes.put("GSA_G61",381);
		labels.put(381, new ArrayList<Label>());
		values.put(382,"Goods Services Administration-G62");
		shortCodes.put("GSA_G62",382);
		labels.put(382, new ArrayList<Label>());
		values.put(383,"Goods Services Administration-G63");
		shortCodes.put("GSA_G63",383);
		labels.put(383, new ArrayList<Label>());
		values.put(384,"Goods Services Administration-G71");
		shortCodes.put("GSA_G71",384);
		labels.put(384, new ArrayList<Label>());
		values.put(385,"Goods Services Administration-G82");
		shortCodes.put("GSA_G82",385);
		labels.put(385, new ArrayList<Label>());
		values.put(386,"Goods Services Administration-G87");
		shortCodes.put("GSA_G87",386);
		labels.put(386, new ArrayList<Label>());
		values.put(387,"Goods Services Administration-G90");
		shortCodes.put("GSA_G90",387);
		labels.put(387, new ArrayList<Label>());
		values.put(388,"Goods Services Administration-N58");
		shortCodes.put("GSA_N58",388);
		labels.put(388, new ArrayList<Label>());
	}

	@Override
	public LinkedHashMap<Integer, String> getHashmap() {
		return values;
	}

	@Override
	public LinkedHashMap<String, Integer> getShortCodes() {
		return shortCodes;
	}
	@Override
	public LinkedHashMap<Integer, ArrayList<Label>> getLabels() {
		return labels;
	}
}