CREATE  VIEW testrunner.EVENTFOLDERPATHS AS
SELECT
	EVENTDEFFOLDERUuid,
    PARENTFOLDERUuid,
    DESCRIPTION,
    testrunner.GETEVENTFOLDERPATH(EVENTDEFFOLDERUuid) AS FOLDERPATH
FROM testrunner.EVENTDEFFOLDER;      
