package com.jsantos.metadata;

import com.jsantos.orm.mt.MTBase; 
import com.jsantos.metadata.config.*;
import com.jsantos.metadata.audit.*;

public class MTDataGridSettingData extends MTBase{ 
	static boolean initialized = false;

	public static MTTableDATAGRIDSETTING DATAGRIDSETTING;
	public static MTTableINPUTSOURCE INPUTSOURCE;
	public static MTTableINPUTUSER INPUTUSER;
	public static MTTableINPUTUSERGROUP INPUTUSERGROUP;
	public static MTTableUSERGROUP USERGROUP;
	public static MTTableVUSERMULTIGROUP VUSERMULTIGROUP;
	public static MTTableVINPUTUSER VINPUTUSER;
	public static MTTableVINPUTUSERMULTI VINPUTUSERMULTI;
	public static MTTableVUSERGROUP VUSERGROUP;
	public static MTTableAPPDATATYPE APPDATATYPE;
	public static MTTableAPPINFO APPINFO;
	public static MTTableAPPINFOTREE APPINFOTREE;
	public static MTTablePOSTINGDATE POSTINGDATE;

	public static void init(){
		if (initialized) return;
		initialized = true;

		MTDataGridSettingData.init();
		MTAuditData.init();
		DATAGRIDSETTING = new MTTableDATAGRIDSETTING();
		INPUTSOURCE = new MTTableINPUTSOURCE();
		INPUTUSER = new MTTableINPUTUSER();
		INPUTUSERGROUP = new MTTableINPUTUSERGROUP();
		USERGROUP = new MTTableUSERGROUP();
		VUSERMULTIGROUP = new MTTableVUSERMULTIGROUP();
		VINPUTUSER = new MTTableVINPUTUSER();
		VINPUTUSERMULTI = new MTTableVINPUTUSERMULTI();
		VUSERGROUP = new MTTableVUSERGROUP();
		APPDATATYPE = new MTTableAPPDATATYPE();
		APPINFO = new MTTableAPPINFO();
		APPINFOTREE = new MTTableAPPINFOTREE();
		POSTINGDATE = new MTTablePOSTINGDATE();

		tables.put("DATAGRIDSETTING", DATAGRIDSETTING);
		tables.put("INPUTSOURCE", INPUTSOURCE);
		tables.put("INPUTUSER", INPUTUSER);
		tables.put("INPUTUSERGROUP", INPUTUSERGROUP);
		tables.put("USERGROUP", USERGROUP);
		tables.put("VUSERMULTIGROUP", VUSERMULTIGROUP);
		tables.put("VINPUTUSER", VINPUTUSER);
		tables.put("VINPUTUSERMULTI", VINPUTUSERMULTI);
		tables.put("VUSERGROUP", VUSERGROUP);
		tables.put("APPDATATYPE", APPDATATYPE);
		tables.put("APPINFO", APPINFO);
		tables.put("APPINFOTREE", APPINFOTREE);
		tables.put("POSTINGDATE", POSTINGDATE);

		MTTableDATAGRIDSETTING.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableDATAGRIDSETTING.INPUTUSERID.setForeignKey(INPUTUSER);
		MTTableDATAGRIDSETTING.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableINPUTUSER.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableUSERGROUP.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableUSERGROUP.USERID.setForeignKey(INPUTUSER);
		MTTableUSERGROUP.INPUTUSERID.setForeignKey(INPUTUSER);
		MTTableUSERGROUP.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableVUSERMULTIGROUP.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableVUSERMULTIGROUP.USERGROUPS.setMultiRefTo(USERGROUP);
		MTTableVINPUTUSER.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableVINPUTUSERMULTI.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableVINPUTUSERMULTI.USERGROUPS.setMultiRefTo(USERGROUP);
		MTTableVUSERGROUP.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableVUSERGROUP.USERID.setForeignKey(INPUTUSER);
		MTTableVUSERGROUP.INPUTUSERID.setForeignKey(INPUTUSER);
		MTTableVUSERGROUP.INPUTSOURCEID.setForeignKey(INPUTSOURCE);
		MTTableAPPINFO.TYPE.setForeignKey(APPDATATYPE);
		MTTableAPPINFO.INPUTUSERGROUPID.setForeignKey(INPUTUSERGROUP);
		MTTableAPPINFOTREE.PARENTAPPINFOTREEID.setForeignKey(APPINFOTREE);
		MTTableAPPINFOTREE.APPINFOID.setForeignKey(APPINFO);

	}
} 

