/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.DataTypeDetails;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type Details</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.DataTypeDetailsImpl#getDbNativeType <em>Db Native Type</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.DataTypeDetailsImpl#isWithPrecissionAndScale <em>With Precission And Scale</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.DataTypeDetailsImpl#isWithLength <em>With Length</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.DataTypeDetailsImpl#getJavaType <em>Java Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataTypeDetailsImpl extends DataTypeDefinitionImpl implements DataTypeDetails
{
  /**
   * The default value of the '{@link #getDbNativeType() <em>Db Native Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDbNativeType()
   * @generated
   * @ordered
   */
  protected static final String DB_NATIVE_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDbNativeType() <em>Db Native Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDbNativeType()
   * @generated
   * @ordered
   */
  protected String dbNativeType = DB_NATIVE_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #isWithPrecissionAndScale() <em>With Precission And Scale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isWithPrecissionAndScale()
   * @generated
   * @ordered
   */
  protected static final boolean WITH_PRECISSION_AND_SCALE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isWithPrecissionAndScale() <em>With Precission And Scale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isWithPrecissionAndScale()
   * @generated
   * @ordered
   */
  protected boolean withPrecissionAndScale = WITH_PRECISSION_AND_SCALE_EDEFAULT;

  /**
   * The default value of the '{@link #isWithLength() <em>With Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isWithLength()
   * @generated
   * @ordered
   */
  protected static final boolean WITH_LENGTH_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isWithLength() <em>With Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isWithLength()
   * @generated
   * @ordered
   */
  protected boolean withLength = WITH_LENGTH_EDEFAULT;

  /**
   * The default value of the '{@link #getJavaType() <em>Java Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJavaType()
   * @generated
   * @ordered
   */
  protected static final String JAVA_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJavaType() <em>Java Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJavaType()
   * @generated
   * @ordered
   */
  protected String javaType = JAVA_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeDetailsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.DATA_TYPE_DETAILS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDbNativeType()
  {
    return dbNativeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDbNativeType(String newDbNativeType)
  {
    String oldDbNativeType = dbNativeType;
    dbNativeType = newDbNativeType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.DATA_TYPE_DETAILS__DB_NATIVE_TYPE, oldDbNativeType, dbNativeType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isWithPrecissionAndScale()
  {
    return withPrecissionAndScale;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWithPrecissionAndScale(boolean newWithPrecissionAndScale)
  {
    boolean oldWithPrecissionAndScale = withPrecissionAndScale;
    withPrecissionAndScale = newWithPrecissionAndScale;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.DATA_TYPE_DETAILS__WITH_PRECISSION_AND_SCALE, oldWithPrecissionAndScale, withPrecissionAndScale));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isWithLength()
  {
    return withLength;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWithLength(boolean newWithLength)
  {
    boolean oldWithLength = withLength;
    withLength = newWithLength;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.DATA_TYPE_DETAILS__WITH_LENGTH, oldWithLength, withLength));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getJavaType()
  {
    return javaType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJavaType(String newJavaType)
  {
    String oldJavaType = javaType;
    javaType = newJavaType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.DATA_TYPE_DETAILS__JAVA_TYPE, oldJavaType, javaType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.DATA_TYPE_DETAILS__DB_NATIVE_TYPE:
        return getDbNativeType();
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_PRECISSION_AND_SCALE:
        return isWithPrecissionAndScale();
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_LENGTH:
        return isWithLength();
      case MetaDslPackage.DATA_TYPE_DETAILS__JAVA_TYPE:
        return getJavaType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.DATA_TYPE_DETAILS__DB_NATIVE_TYPE:
        setDbNativeType((String)newValue);
        return;
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_PRECISSION_AND_SCALE:
        setWithPrecissionAndScale((Boolean)newValue);
        return;
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_LENGTH:
        setWithLength((Boolean)newValue);
        return;
      case MetaDslPackage.DATA_TYPE_DETAILS__JAVA_TYPE:
        setJavaType((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.DATA_TYPE_DETAILS__DB_NATIVE_TYPE:
        setDbNativeType(DB_NATIVE_TYPE_EDEFAULT);
        return;
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_PRECISSION_AND_SCALE:
        setWithPrecissionAndScale(WITH_PRECISSION_AND_SCALE_EDEFAULT);
        return;
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_LENGTH:
        setWithLength(WITH_LENGTH_EDEFAULT);
        return;
      case MetaDslPackage.DATA_TYPE_DETAILS__JAVA_TYPE:
        setJavaType(JAVA_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.DATA_TYPE_DETAILS__DB_NATIVE_TYPE:
        return DB_NATIVE_TYPE_EDEFAULT == null ? dbNativeType != null : !DB_NATIVE_TYPE_EDEFAULT.equals(dbNativeType);
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_PRECISSION_AND_SCALE:
        return withPrecissionAndScale != WITH_PRECISSION_AND_SCALE_EDEFAULT;
      case MetaDslPackage.DATA_TYPE_DETAILS__WITH_LENGTH:
        return withLength != WITH_LENGTH_EDEFAULT;
      case MetaDslPackage.DATA_TYPE_DETAILS__JAVA_TYPE:
        return JAVA_TYPE_EDEFAULT == null ? javaType != null : !JAVA_TYPE_EDEFAULT.equals(javaType);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dbNativeType: ");
    result.append(dbNativeType);
    result.append(", withPrecissionAndScale: ");
    result.append(withPrecissionAndScale);
    result.append(", withLength: ");
    result.append(withLength);
    result.append(", javaType: ");
    result.append(javaType);
    result.append(')');
    return result.toString();
  }

} //DataTypeDetailsImpl
