/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.Attribute;
import com.jsantos.metadata.plugin.metaDsl.DocumentationBlock;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Documentation Block</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.DocumentationBlockImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.DocumentationBlockImpl#getDocumentationText <em>Documentation Text</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DocumentationBlockImpl extends MinimalEObjectImpl.Container implements DocumentationBlock
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The default value of the '{@link #getDocumentationText() <em>Documentation Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDocumentationText()
   * @generated
   * @ordered
   */
  protected static final String DOCUMENTATION_TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDocumentationText() <em>Documentation Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDocumentationText()
   * @generated
   * @ordered
   */
  protected String documentationText = DOCUMENTATION_TEXT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DocumentationBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.DOCUMENTATION_BLOCK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttribute()
  {
    if (attribute != null && attribute.eIsProxy())
    {
      InternalEObject oldAttribute = (InternalEObject)attribute;
      attribute = (Attribute)eResolveProxy(oldAttribute);
      if (attribute != oldAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MetaDslPackage.DOCUMENTATION_BLOCK__ATTRIBUTE, oldAttribute, attribute));
      }
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttribute(Attribute newAttribute)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.DOCUMENTATION_BLOCK__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDocumentationText()
  {
    return documentationText;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDocumentationText(String newDocumentationText)
  {
    String oldDocumentationText = documentationText;
    documentationText = newDocumentationText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.DOCUMENTATION_BLOCK__DOCUMENTATION_TEXT, oldDocumentationText, documentationText));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.DOCUMENTATION_BLOCK__ATTRIBUTE:
        if (resolve) return getAttribute();
        return basicGetAttribute();
      case MetaDslPackage.DOCUMENTATION_BLOCK__DOCUMENTATION_TEXT:
        return getDocumentationText();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.DOCUMENTATION_BLOCK__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case MetaDslPackage.DOCUMENTATION_BLOCK__DOCUMENTATION_TEXT:
        setDocumentationText((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.DOCUMENTATION_BLOCK__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case MetaDslPackage.DOCUMENTATION_BLOCK__DOCUMENTATION_TEXT:
        setDocumentationText(DOCUMENTATION_TEXT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.DOCUMENTATION_BLOCK__ATTRIBUTE:
        return attribute != null;
      case MetaDslPackage.DOCUMENTATION_BLOCK__DOCUMENTATION_TEXT:
        return DOCUMENTATION_TEXT_EDEFAULT == null ? documentationText != null : !DOCUMENTATION_TEXT_EDEFAULT.equals(documentationText);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (documentationText: ");
    result.append(documentationText);
    result.append(')');
    return result.toString();
  }

} //DocumentationBlockImpl
