/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.Attribute;
import com.jsantos.metadata.plugin.metaDsl.DocumentationSection;
import com.jsantos.metadata.plugin.metaDsl.Entity;
import com.jsantos.metadata.plugin.metaDsl.EnuMetadata;
import com.jsantos.metadata.plugin.metaDsl.EnumerationLabels;
import com.jsantos.metadata.plugin.metaDsl.LabelSection;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.Metadata;
import com.jsantos.metadata.plugin.metaDsl.Pattern;
import com.jsantos.metadata.plugin.metaDsl.QuerySourceBlock;
import com.jsantos.metadata.plugin.metaDsl.SqlFileDependency;
import com.jsantos.metadata.plugin.metaDsl.TableStereotype;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getFromSQLFile <em>From SQL File</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getSqlFileDependencies <em>Sql File Dependencies</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getEntityType <em>Entity Type</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getExtends <em>Extends</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getPatterns <em>Patterns</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getStereotypes <em>Stereotypes</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getEnuMetadata <em>Enu Metadata</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getLabelSection <em>Label Section</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getEnumerationLabels <em>Enumeration Labels</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getDocumentationSection <em>Documentation Section</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EntityImpl#getQuerySourceBlock <em>Query Source Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EntityImpl extends MinimalEObjectImpl.Container implements Entity
{
  /**
   * The default value of the '{@link #getFromSQLFile() <em>From SQL File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromSQLFile()
   * @generated
   * @ordered
   */
  protected static final String FROM_SQL_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFromSQLFile() <em>From SQL File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromSQLFile()
   * @generated
   * @ordered
   */
  protected String fromSQLFile = FROM_SQL_FILE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSqlFileDependencies() <em>Sql File Dependencies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSqlFileDependencies()
   * @generated
   * @ordered
   */
  protected EList<SqlFileDependency> sqlFileDependencies;

  /**
   * The default value of the '{@link #getEntityType() <em>Entity Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityType()
   * @generated
   * @ordered
   */
  protected static final String ENTITY_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntityType() <em>Entity Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityType()
   * @generated
   * @ordered
   */
  protected String entityType = ENTITY_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getExtends() <em>Extends</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtends()
   * @generated
   * @ordered
   */
  protected Entity extends_;

  /**
   * The cached value of the '{@link #getPatterns() <em>Patterns</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatterns()
   * @generated
   * @ordered
   */
  protected EList<Pattern> patterns;

  /**
   * The cached value of the '{@link #getStereotypes() <em>Stereotypes</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStereotypes()
   * @generated
   * @ordered
   */
  protected EList<TableStereotype> stereotypes;

  /**
   * The cached value of the '{@link #getAttributes() <em>Attributes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributes()
   * @generated
   * @ordered
   */
  protected EList<Attribute> attributes;

  /**
   * The cached value of the '{@link #getMetadata() <em>Metadata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetadata()
   * @generated
   * @ordered
   */
  protected Metadata metadata;

  /**
   * The cached value of the '{@link #getEnuMetadata() <em>Enu Metadata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnuMetadata()
   * @generated
   * @ordered
   */
  protected EnuMetadata enuMetadata;

  /**
   * The cached value of the '{@link #getLabelSection() <em>Label Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabelSection()
   * @generated
   * @ordered
   */
  protected LabelSection labelSection;

  /**
   * The cached value of the '{@link #getEnumerationLabels() <em>Enumeration Labels</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerationLabels()
   * @generated
   * @ordered
   */
  protected EnumerationLabels enumerationLabels;

  /**
   * The cached value of the '{@link #getDocumentationSection() <em>Documentation Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDocumentationSection()
   * @generated
   * @ordered
   */
  protected DocumentationSection documentationSection;

  /**
   * The cached value of the '{@link #getQuerySourceBlock() <em>Query Source Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuerySourceBlock()
   * @generated
   * @ordered
   */
  protected QuerySourceBlock querySourceBlock;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.ENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFromSQLFile()
  {
    return fromSQLFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFromSQLFile(String newFromSQLFile)
  {
    String oldFromSQLFile = fromSQLFile;
    fromSQLFile = newFromSQLFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__FROM_SQL_FILE, oldFromSQLFile, fromSQLFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SqlFileDependency> getSqlFileDependencies()
  {
    if (sqlFileDependencies == null)
    {
      sqlFileDependencies = new EObjectContainmentEList<SqlFileDependency>(SqlFileDependency.class, this, MetaDslPackage.ENTITY__SQL_FILE_DEPENDENCIES);
    }
    return sqlFileDependencies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEntityType()
  {
    return entityType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntityType(String newEntityType)
  {
    String oldEntityType = entityType;
    entityType = newEntityType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__ENTITY_TYPE, oldEntityType, entityType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entity getExtends()
  {
    if (extends_ != null && extends_.eIsProxy())
    {
      InternalEObject oldExtends = (InternalEObject)extends_;
      extends_ = (Entity)eResolveProxy(oldExtends);
      if (extends_ != oldExtends)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MetaDslPackage.ENTITY__EXTENDS, oldExtends, extends_));
      }
    }
    return extends_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity basicGetExtends()
  {
    return extends_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExtends(Entity newExtends)
  {
    Entity oldExtends = extends_;
    extends_ = newExtends;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__EXTENDS, oldExtends, extends_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Pattern> getPatterns()
  {
    if (patterns == null)
    {
      patterns = new EObjectResolvingEList<Pattern>(Pattern.class, this, MetaDslPackage.ENTITY__PATTERNS);
    }
    return patterns;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TableStereotype> getStereotypes()
  {
    if (stereotypes == null)
    {
      stereotypes = new EObjectResolvingEList<TableStereotype>(TableStereotype.class, this, MetaDslPackage.ENTITY__STEREOTYPES);
    }
    return stereotypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Attribute> getAttributes()
  {
    if (attributes == null)
    {
      attributes = new EObjectContainmentEList<Attribute>(Attribute.class, this, MetaDslPackage.ENTITY__ATTRIBUTES);
    }
    return attributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metadata getMetadata()
  {
    return metadata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMetadata(Metadata newMetadata, NotificationChain msgs)
  {
    Metadata oldMetadata = metadata;
    metadata = newMetadata;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__METADATA, oldMetadata, newMetadata);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMetadata(Metadata newMetadata)
  {
    if (newMetadata != metadata)
    {
      NotificationChain msgs = null;
      if (metadata != null)
        msgs = ((InternalEObject)metadata).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__METADATA, null, msgs);
      if (newMetadata != null)
        msgs = ((InternalEObject)newMetadata).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__METADATA, null, msgs);
      msgs = basicSetMetadata(newMetadata, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__METADATA, newMetadata, newMetadata));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnuMetadata getEnuMetadata()
  {
    return enuMetadata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnuMetadata(EnuMetadata newEnuMetadata, NotificationChain msgs)
  {
    EnuMetadata oldEnuMetadata = enuMetadata;
    enuMetadata = newEnuMetadata;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__ENU_METADATA, oldEnuMetadata, newEnuMetadata);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnuMetadata(EnuMetadata newEnuMetadata)
  {
    if (newEnuMetadata != enuMetadata)
    {
      NotificationChain msgs = null;
      if (enuMetadata != null)
        msgs = ((InternalEObject)enuMetadata).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__ENU_METADATA, null, msgs);
      if (newEnuMetadata != null)
        msgs = ((InternalEObject)newEnuMetadata).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__ENU_METADATA, null, msgs);
      msgs = basicSetEnuMetadata(newEnuMetadata, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__ENU_METADATA, newEnuMetadata, newEnuMetadata));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LabelSection getLabelSection()
  {
    return labelSection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLabelSection(LabelSection newLabelSection, NotificationChain msgs)
  {
    LabelSection oldLabelSection = labelSection;
    labelSection = newLabelSection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__LABEL_SECTION, oldLabelSection, newLabelSection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLabelSection(LabelSection newLabelSection)
  {
    if (newLabelSection != labelSection)
    {
      NotificationChain msgs = null;
      if (labelSection != null)
        msgs = ((InternalEObject)labelSection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__LABEL_SECTION, null, msgs);
      if (newLabelSection != null)
        msgs = ((InternalEObject)newLabelSection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__LABEL_SECTION, null, msgs);
      msgs = basicSetLabelSection(newLabelSection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__LABEL_SECTION, newLabelSection, newLabelSection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnumerationLabels getEnumerationLabels()
  {
    return enumerationLabels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumerationLabels(EnumerationLabels newEnumerationLabels, NotificationChain msgs)
  {
    EnumerationLabels oldEnumerationLabels = enumerationLabels;
    enumerationLabels = newEnumerationLabels;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__ENUMERATION_LABELS, oldEnumerationLabels, newEnumerationLabels);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnumerationLabels(EnumerationLabels newEnumerationLabels)
  {
    if (newEnumerationLabels != enumerationLabels)
    {
      NotificationChain msgs = null;
      if (enumerationLabels != null)
        msgs = ((InternalEObject)enumerationLabels).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__ENUMERATION_LABELS, null, msgs);
      if (newEnumerationLabels != null)
        msgs = ((InternalEObject)newEnumerationLabels).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__ENUMERATION_LABELS, null, msgs);
      msgs = basicSetEnumerationLabels(newEnumerationLabels, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__ENUMERATION_LABELS, newEnumerationLabels, newEnumerationLabels));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DocumentationSection getDocumentationSection()
  {
    return documentationSection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDocumentationSection(DocumentationSection newDocumentationSection, NotificationChain msgs)
  {
    DocumentationSection oldDocumentationSection = documentationSection;
    documentationSection = newDocumentationSection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__DOCUMENTATION_SECTION, oldDocumentationSection, newDocumentationSection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDocumentationSection(DocumentationSection newDocumentationSection)
  {
    if (newDocumentationSection != documentationSection)
    {
      NotificationChain msgs = null;
      if (documentationSection != null)
        msgs = ((InternalEObject)documentationSection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__DOCUMENTATION_SECTION, null, msgs);
      if (newDocumentationSection != null)
        msgs = ((InternalEObject)newDocumentationSection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__DOCUMENTATION_SECTION, null, msgs);
      msgs = basicSetDocumentationSection(newDocumentationSection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__DOCUMENTATION_SECTION, newDocumentationSection, newDocumentationSection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuerySourceBlock getQuerySourceBlock()
  {
    return querySourceBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQuerySourceBlock(QuerySourceBlock newQuerySourceBlock, NotificationChain msgs)
  {
    QuerySourceBlock oldQuerySourceBlock = querySourceBlock;
    querySourceBlock = newQuerySourceBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK, oldQuerySourceBlock, newQuerySourceBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQuerySourceBlock(QuerySourceBlock newQuerySourceBlock)
  {
    if (newQuerySourceBlock != querySourceBlock)
    {
      NotificationChain msgs = null;
      if (querySourceBlock != null)
        msgs = ((InternalEObject)querySourceBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK, null, msgs);
      if (newQuerySourceBlock != null)
        msgs = ((InternalEObject)newQuerySourceBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK, null, msgs);
      msgs = basicSetQuerySourceBlock(newQuerySourceBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK, newQuerySourceBlock, newQuerySourceBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENTITY__SQL_FILE_DEPENDENCIES:
        return ((InternalEList<?>)getSqlFileDependencies()).basicRemove(otherEnd, msgs);
      case MetaDslPackage.ENTITY__ATTRIBUTES:
        return ((InternalEList<?>)getAttributes()).basicRemove(otherEnd, msgs);
      case MetaDslPackage.ENTITY__METADATA:
        return basicSetMetadata(null, msgs);
      case MetaDslPackage.ENTITY__ENU_METADATA:
        return basicSetEnuMetadata(null, msgs);
      case MetaDslPackage.ENTITY__LABEL_SECTION:
        return basicSetLabelSection(null, msgs);
      case MetaDslPackage.ENTITY__ENUMERATION_LABELS:
        return basicSetEnumerationLabels(null, msgs);
      case MetaDslPackage.ENTITY__DOCUMENTATION_SECTION:
        return basicSetDocumentationSection(null, msgs);
      case MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK:
        return basicSetQuerySourceBlock(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENTITY__FROM_SQL_FILE:
        return getFromSQLFile();
      case MetaDslPackage.ENTITY__SQL_FILE_DEPENDENCIES:
        return getSqlFileDependencies();
      case MetaDslPackage.ENTITY__ENTITY_TYPE:
        return getEntityType();
      case MetaDslPackage.ENTITY__NAME:
        return getName();
      case MetaDslPackage.ENTITY__EXTENDS:
        if (resolve) return getExtends();
        return basicGetExtends();
      case MetaDslPackage.ENTITY__PATTERNS:
        return getPatterns();
      case MetaDslPackage.ENTITY__STEREOTYPES:
        return getStereotypes();
      case MetaDslPackage.ENTITY__ATTRIBUTES:
        return getAttributes();
      case MetaDslPackage.ENTITY__METADATA:
        return getMetadata();
      case MetaDslPackage.ENTITY__ENU_METADATA:
        return getEnuMetadata();
      case MetaDslPackage.ENTITY__LABEL_SECTION:
        return getLabelSection();
      case MetaDslPackage.ENTITY__ENUMERATION_LABELS:
        return getEnumerationLabels();
      case MetaDslPackage.ENTITY__DOCUMENTATION_SECTION:
        return getDocumentationSection();
      case MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK:
        return getQuerySourceBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENTITY__FROM_SQL_FILE:
        setFromSQLFile((String)newValue);
        return;
      case MetaDslPackage.ENTITY__SQL_FILE_DEPENDENCIES:
        getSqlFileDependencies().clear();
        getSqlFileDependencies().addAll((Collection<? extends SqlFileDependency>)newValue);
        return;
      case MetaDslPackage.ENTITY__ENTITY_TYPE:
        setEntityType((String)newValue);
        return;
      case MetaDslPackage.ENTITY__NAME:
        setName((String)newValue);
        return;
      case MetaDslPackage.ENTITY__EXTENDS:
        setExtends((Entity)newValue);
        return;
      case MetaDslPackage.ENTITY__PATTERNS:
        getPatterns().clear();
        getPatterns().addAll((Collection<? extends Pattern>)newValue);
        return;
      case MetaDslPackage.ENTITY__STEREOTYPES:
        getStereotypes().clear();
        getStereotypes().addAll((Collection<? extends TableStereotype>)newValue);
        return;
      case MetaDslPackage.ENTITY__ATTRIBUTES:
        getAttributes().clear();
        getAttributes().addAll((Collection<? extends Attribute>)newValue);
        return;
      case MetaDslPackage.ENTITY__METADATA:
        setMetadata((Metadata)newValue);
        return;
      case MetaDslPackage.ENTITY__ENU_METADATA:
        setEnuMetadata((EnuMetadata)newValue);
        return;
      case MetaDslPackage.ENTITY__LABEL_SECTION:
        setLabelSection((LabelSection)newValue);
        return;
      case MetaDslPackage.ENTITY__ENUMERATION_LABELS:
        setEnumerationLabels((EnumerationLabels)newValue);
        return;
      case MetaDslPackage.ENTITY__DOCUMENTATION_SECTION:
        setDocumentationSection((DocumentationSection)newValue);
        return;
      case MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK:
        setQuerySourceBlock((QuerySourceBlock)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENTITY__FROM_SQL_FILE:
        setFromSQLFile(FROM_SQL_FILE_EDEFAULT);
        return;
      case MetaDslPackage.ENTITY__SQL_FILE_DEPENDENCIES:
        getSqlFileDependencies().clear();
        return;
      case MetaDslPackage.ENTITY__ENTITY_TYPE:
        setEntityType(ENTITY_TYPE_EDEFAULT);
        return;
      case MetaDslPackage.ENTITY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MetaDslPackage.ENTITY__EXTENDS:
        setExtends((Entity)null);
        return;
      case MetaDslPackage.ENTITY__PATTERNS:
        getPatterns().clear();
        return;
      case MetaDslPackage.ENTITY__STEREOTYPES:
        getStereotypes().clear();
        return;
      case MetaDslPackage.ENTITY__ATTRIBUTES:
        getAttributes().clear();
        return;
      case MetaDslPackage.ENTITY__METADATA:
        setMetadata((Metadata)null);
        return;
      case MetaDslPackage.ENTITY__ENU_METADATA:
        setEnuMetadata((EnuMetadata)null);
        return;
      case MetaDslPackage.ENTITY__LABEL_SECTION:
        setLabelSection((LabelSection)null);
        return;
      case MetaDslPackage.ENTITY__ENUMERATION_LABELS:
        setEnumerationLabels((EnumerationLabels)null);
        return;
      case MetaDslPackage.ENTITY__DOCUMENTATION_SECTION:
        setDocumentationSection((DocumentationSection)null);
        return;
      case MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK:
        setQuerySourceBlock((QuerySourceBlock)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENTITY__FROM_SQL_FILE:
        return FROM_SQL_FILE_EDEFAULT == null ? fromSQLFile != null : !FROM_SQL_FILE_EDEFAULT.equals(fromSQLFile);
      case MetaDslPackage.ENTITY__SQL_FILE_DEPENDENCIES:
        return sqlFileDependencies != null && !sqlFileDependencies.isEmpty();
      case MetaDslPackage.ENTITY__ENTITY_TYPE:
        return ENTITY_TYPE_EDEFAULT == null ? entityType != null : !ENTITY_TYPE_EDEFAULT.equals(entityType);
      case MetaDslPackage.ENTITY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MetaDslPackage.ENTITY__EXTENDS:
        return extends_ != null;
      case MetaDslPackage.ENTITY__PATTERNS:
        return patterns != null && !patterns.isEmpty();
      case MetaDslPackage.ENTITY__STEREOTYPES:
        return stereotypes != null && !stereotypes.isEmpty();
      case MetaDslPackage.ENTITY__ATTRIBUTES:
        return attributes != null && !attributes.isEmpty();
      case MetaDslPackage.ENTITY__METADATA:
        return metadata != null;
      case MetaDslPackage.ENTITY__ENU_METADATA:
        return enuMetadata != null;
      case MetaDslPackage.ENTITY__LABEL_SECTION:
        return labelSection != null;
      case MetaDslPackage.ENTITY__ENUMERATION_LABELS:
        return enumerationLabels != null;
      case MetaDslPackage.ENTITY__DOCUMENTATION_SECTION:
        return documentationSection != null;
      case MetaDslPackage.ENTITY__QUERY_SOURCE_BLOCK:
        return querySourceBlock != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (fromSQLFile: ");
    result.append(fromSQLFile);
    result.append(", entityType: ");
    result.append(entityType);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EntityImpl
