/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.EnumerationLabel;
import com.jsantos.metadata.plugin.metaDsl.EnumerationLabels;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enumeration Labels</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EnumerationLabelsImpl#getEnumerationLabel <em>Enumeration Label</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumerationLabelsImpl extends MinimalEObjectImpl.Container implements EnumerationLabels
{
  /**
   * The cached value of the '{@link #getEnumerationLabel() <em>Enumeration Label</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerationLabel()
   * @generated
   * @ordered
   */
  protected EList<EnumerationLabel> enumerationLabel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumerationLabelsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.ENUMERATION_LABELS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnumerationLabel> getEnumerationLabel()
  {
    if (enumerationLabel == null)
    {
      enumerationLabel = new EObjectContainmentEList<EnumerationLabel>(EnumerationLabel.class, this, MetaDslPackage.ENUMERATION_LABELS__ENUMERATION_LABEL);
    }
    return enumerationLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENUMERATION_LABELS__ENUMERATION_LABEL:
        return ((InternalEList<?>)getEnumerationLabel()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENUMERATION_LABELS__ENUMERATION_LABEL:
        return getEnumerationLabel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENUMERATION_LABELS__ENUMERATION_LABEL:
        getEnumerationLabel().clear();
        getEnumerationLabel().addAll((Collection<? extends EnumerationLabel>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENUMERATION_LABELS__ENUMERATION_LABEL:
        getEnumerationLabel().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENUMERATION_LABELS__ENUMERATION_LABEL:
        return enumerationLabel != null && !enumerationLabel.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //EnumerationLabelsImpl
