/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.EnuMetadata;
import com.jsantos.metadata.plugin.metaDsl.EnuMetadataRow;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enu Metadata</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.EnuMetadataImpl#getEnuMetadataRows <em>Enu Metadata Rows</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnuMetadataImpl extends MinimalEObjectImpl.Container implements EnuMetadata
{
  /**
   * The cached value of the '{@link #getEnuMetadataRows() <em>Enu Metadata Rows</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnuMetadataRows()
   * @generated
   * @ordered
   */
  protected EList<EnuMetadataRow> enuMetadataRows;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnuMetadataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.ENU_METADATA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnuMetadataRow> getEnuMetadataRows()
  {
    if (enuMetadataRows == null)
    {
      enuMetadataRows = new EObjectContainmentEList<EnuMetadataRow>(EnuMetadataRow.class, this, MetaDslPackage.ENU_METADATA__ENU_METADATA_ROWS);
    }
    return enuMetadataRows;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENU_METADATA__ENU_METADATA_ROWS:
        return ((InternalEList<?>)getEnuMetadataRows()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENU_METADATA__ENU_METADATA_ROWS:
        return getEnuMetadataRows();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENU_METADATA__ENU_METADATA_ROWS:
        getEnuMetadataRows().clear();
        getEnuMetadataRows().addAll((Collection<? extends EnuMetadataRow>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENU_METADATA__ENU_METADATA_ROWS:
        getEnuMetadataRows().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ENU_METADATA__ENU_METADATA_ROWS:
        return enuMetadataRows != null && !enuMetadataRows.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //EnuMetadataImpl
