/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.GeneralLabelSection;
import com.jsantos.metadata.plugin.metaDsl.KeyLabel;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>General Label Section</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.GeneralLabelSectionImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.GeneralLabelSectionImpl#getKeyLabel <em>Key Label</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.GeneralLabelSectionImpl#getOverrideLabelBlock <em>Override Label Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GeneralLabelSectionImpl extends MinimalEObjectImpl.Container implements GeneralLabelSection
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getKeyLabel() <em>Key Label</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyLabel()
   * @generated
   * @ordered
   */
  protected EList<KeyLabel> keyLabel;

  /**
   * The cached value of the '{@link #getOverrideLabelBlock() <em>Override Label Block</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOverrideLabelBlock()
   * @generated
   * @ordered
   */
  protected EList<OverrideLabelBlock> overrideLabelBlock;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeneralLabelSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.GENERAL_LABEL_SECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.GENERAL_LABEL_SECTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<KeyLabel> getKeyLabel()
  {
    if (keyLabel == null)
    {
      keyLabel = new EObjectContainmentEList<KeyLabel>(KeyLabel.class, this, MetaDslPackage.GENERAL_LABEL_SECTION__KEY_LABEL);
    }
    return keyLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<OverrideLabelBlock> getOverrideLabelBlock()
  {
    if (overrideLabelBlock == null)
    {
      overrideLabelBlock = new EObjectContainmentEList<OverrideLabelBlock>(OverrideLabelBlock.class, this, MetaDslPackage.GENERAL_LABEL_SECTION__OVERRIDE_LABEL_BLOCK);
    }
    return overrideLabelBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.GENERAL_LABEL_SECTION__KEY_LABEL:
        return ((InternalEList<?>)getKeyLabel()).basicRemove(otherEnd, msgs);
      case MetaDslPackage.GENERAL_LABEL_SECTION__OVERRIDE_LABEL_BLOCK:
        return ((InternalEList<?>)getOverrideLabelBlock()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.GENERAL_LABEL_SECTION__NAME:
        return getName();
      case MetaDslPackage.GENERAL_LABEL_SECTION__KEY_LABEL:
        return getKeyLabel();
      case MetaDslPackage.GENERAL_LABEL_SECTION__OVERRIDE_LABEL_BLOCK:
        return getOverrideLabelBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.GENERAL_LABEL_SECTION__NAME:
        setName((String)newValue);
        return;
      case MetaDslPackage.GENERAL_LABEL_SECTION__KEY_LABEL:
        getKeyLabel().clear();
        getKeyLabel().addAll((Collection<? extends KeyLabel>)newValue);
        return;
      case MetaDslPackage.GENERAL_LABEL_SECTION__OVERRIDE_LABEL_BLOCK:
        getOverrideLabelBlock().clear();
        getOverrideLabelBlock().addAll((Collection<? extends OverrideLabelBlock>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.GENERAL_LABEL_SECTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MetaDslPackage.GENERAL_LABEL_SECTION__KEY_LABEL:
        getKeyLabel().clear();
        return;
      case MetaDslPackage.GENERAL_LABEL_SECTION__OVERRIDE_LABEL_BLOCK:
        getOverrideLabelBlock().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.GENERAL_LABEL_SECTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MetaDslPackage.GENERAL_LABEL_SECTION__KEY_LABEL:
        return keyLabel != null && !keyLabel.isEmpty();
      case MetaDslPackage.GENERAL_LABEL_SECTION__OVERRIDE_LABEL_BLOCK:
        return overrideLabelBlock != null && !overrideLabelBlock.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //GeneralLabelSectionImpl
