/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.Attribute;
import com.jsantos.metadata.plugin.metaDsl.IdGenerator;
import com.jsantos.metadata.plugin.metaDsl.IdGeneratorTypeBlock;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Id Generator</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.IdGeneratorImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.IdGeneratorImpl#getTypeBlock <em>Type Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IdGeneratorImpl extends MinimalEObjectImpl.Container implements IdGenerator
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The cached value of the '{@link #getTypeBlock() <em>Type Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeBlock()
   * @generated
   * @ordered
   */
  protected IdGeneratorTypeBlock typeBlock;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IdGeneratorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.ID_GENERATOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttribute()
  {
    if (attribute != null && attribute.eIsProxy())
    {
      InternalEObject oldAttribute = (InternalEObject)attribute;
      attribute = (Attribute)eResolveProxy(oldAttribute);
      if (attribute != oldAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MetaDslPackage.ID_GENERATOR__ATTRIBUTE, oldAttribute, attribute));
      }
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttribute(Attribute newAttribute)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ID_GENERATOR__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IdGeneratorTypeBlock getTypeBlock()
  {
    return typeBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeBlock(IdGeneratorTypeBlock newTypeBlock, NotificationChain msgs)
  {
    IdGeneratorTypeBlock oldTypeBlock = typeBlock;
    typeBlock = newTypeBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaDslPackage.ID_GENERATOR__TYPE_BLOCK, oldTypeBlock, newTypeBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeBlock(IdGeneratorTypeBlock newTypeBlock)
  {
    if (newTypeBlock != typeBlock)
    {
      NotificationChain msgs = null;
      if (typeBlock != null)
        msgs = ((InternalEObject)typeBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ID_GENERATOR__TYPE_BLOCK, null, msgs);
      if (newTypeBlock != null)
        msgs = ((InternalEObject)newTypeBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaDslPackage.ID_GENERATOR__TYPE_BLOCK, null, msgs);
      msgs = basicSetTypeBlock(newTypeBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.ID_GENERATOR__TYPE_BLOCK, newTypeBlock, newTypeBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.ID_GENERATOR__TYPE_BLOCK:
        return basicSetTypeBlock(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.ID_GENERATOR__ATTRIBUTE:
        if (resolve) return getAttribute();
        return basicGetAttribute();
      case MetaDslPackage.ID_GENERATOR__TYPE_BLOCK:
        return getTypeBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.ID_GENERATOR__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case MetaDslPackage.ID_GENERATOR__TYPE_BLOCK:
        setTypeBlock((IdGeneratorTypeBlock)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ID_GENERATOR__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case MetaDslPackage.ID_GENERATOR__TYPE_BLOCK:
        setTypeBlock((IdGeneratorTypeBlock)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.ID_GENERATOR__ATTRIBUTE:
        return attribute != null;
      case MetaDslPackage.ID_GENERATOR__TYPE_BLOCK:
        return typeBlock != null;
    }
    return super.eIsSet(featureID);
  }

} //IdGeneratorImpl
