/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.IdGeneratorSimple;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Id Generator Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IdGeneratorSimpleImpl extends IdGeneratorTypeBlockImpl implements IdGeneratorSimple
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IdGeneratorSimpleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.ID_GENERATOR_SIMPLE;
  }

} //IdGeneratorSimpleImpl
