/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.Attribute;
import com.jsantos.metadata.plugin.metaDsl.Entity;
import com.jsantos.metadata.plugin.metaDsl.EnuMetadataRow;
import com.jsantos.metadata.plugin.metaDsl.Label;
import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.OverrideLabelBlock;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Override Label Block</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.OverrideLabelBlockImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.OverrideLabelBlockImpl#getEntity <em>Entity</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.OverrideLabelBlockImpl#getEnuMetadataRow <em>Enu Metadata Row</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.OverrideLabelBlockImpl#getType <em>Type</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.OverrideLabelBlockImpl#getLabels <em>Labels</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OverrideLabelBlockImpl extends MinimalEObjectImpl.Container implements OverrideLabelBlock
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The cached value of the '{@link #getEntity() <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity()
   * @generated
   * @ordered
   */
  protected Entity entity;

  /**
   * The cached value of the '{@link #getEnuMetadataRow() <em>Enu Metadata Row</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnuMetadataRow()
   * @generated
   * @ordered
   */
  protected EnuMetadataRow enuMetadataRow;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getLabels() <em>Labels</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabels()
   * @generated
   * @ordered
   */
  protected EList<Label> labels;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OverrideLabelBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.OVERRIDE_LABEL_BLOCK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttribute()
  {
    if (attribute != null && attribute.eIsProxy())
    {
      InternalEObject oldAttribute = (InternalEObject)attribute;
      attribute = (Attribute)eResolveProxy(oldAttribute);
      if (attribute != oldAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MetaDslPackage.OVERRIDE_LABEL_BLOCK__ATTRIBUTE, oldAttribute, attribute));
      }
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttribute(Attribute newAttribute)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.OVERRIDE_LABEL_BLOCK__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entity getEntity()
  {
    if (entity != null && entity.eIsProxy())
    {
      InternalEObject oldEntity = (InternalEObject)entity;
      entity = (Entity)eResolveProxy(oldEntity);
      if (entity != oldEntity)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENTITY, oldEntity, entity));
      }
    }
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity basicGetEntity()
  {
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity(Entity newEntity)
  {
    Entity oldEntity = entity;
    entity = newEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENTITY, oldEntity, entity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnuMetadataRow getEnuMetadataRow()
  {
    if (enuMetadataRow != null && enuMetadataRow.eIsProxy())
    {
      InternalEObject oldEnuMetadataRow = (InternalEObject)enuMetadataRow;
      enuMetadataRow = (EnuMetadataRow)eResolveProxy(oldEnuMetadataRow);
      if (enuMetadataRow != oldEnuMetadataRow)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENU_METADATA_ROW, oldEnuMetadataRow, enuMetadataRow));
      }
    }
    return enuMetadataRow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnuMetadataRow basicGetEnuMetadataRow()
  {
    return enuMetadataRow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnuMetadataRow(EnuMetadataRow newEnuMetadataRow)
  {
    EnuMetadataRow oldEnuMetadataRow = enuMetadataRow;
    enuMetadataRow = newEnuMetadataRow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENU_METADATA_ROW, oldEnuMetadataRow, enuMetadataRow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.OVERRIDE_LABEL_BLOCK__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Label> getLabels()
  {
    if (labels == null)
    {
      labels = new EObjectContainmentEList<Label>(Label.class, this, MetaDslPackage.OVERRIDE_LABEL_BLOCK__LABELS);
    }
    return labels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__LABELS:
        return ((InternalEList<?>)getLabels()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ATTRIBUTE:
        if (resolve) return getAttribute();
        return basicGetAttribute();
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENTITY:
        if (resolve) return getEntity();
        return basicGetEntity();
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENU_METADATA_ROW:
        if (resolve) return getEnuMetadataRow();
        return basicGetEnuMetadataRow();
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__TYPE:
        return getType();
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__LABELS:
        return getLabels();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENTITY:
        setEntity((Entity)newValue);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENU_METADATA_ROW:
        setEnuMetadataRow((EnuMetadataRow)newValue);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__TYPE:
        setType((String)newValue);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__LABELS:
        getLabels().clear();
        getLabels().addAll((Collection<? extends Label>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENTITY:
        setEntity((Entity)null);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENU_METADATA_ROW:
        setEnuMetadataRow((EnuMetadataRow)null);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__LABELS:
        getLabels().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ATTRIBUTE:
        return attribute != null;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENTITY:
        return entity != null;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__ENU_METADATA_ROW:
        return enuMetadataRow != null;
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case MetaDslPackage.OVERRIDE_LABEL_BLOCK__LABELS:
        return labels != null && !labels.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //OverrideLabelBlockImpl
