/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.Sequence;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sequence</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#getStartWith <em>Start With</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#getIncrementBy <em>Increment By</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#getMinValue <em>Min Value</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#getMaxValue <em>Max Value</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#isCycle <em>Cycle</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SequenceImpl#getCache <em>Cache</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SequenceImpl extends MinimalEObjectImpl.Container implements Sequence
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getStartWith() <em>Start With</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartWith()
   * @generated
   * @ordered
   */
  protected static final String START_WITH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStartWith() <em>Start With</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartWith()
   * @generated
   * @ordered
   */
  protected String startWith = START_WITH_EDEFAULT;

  /**
   * The default value of the '{@link #getIncrementBy() <em>Increment By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrementBy()
   * @generated
   * @ordered
   */
  protected static final String INCREMENT_BY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIncrementBy() <em>Increment By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrementBy()
   * @generated
   * @ordered
   */
  protected String incrementBy = INCREMENT_BY_EDEFAULT;

  /**
   * The default value of the '{@link #getMinValue() <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinValue()
   * @generated
   * @ordered
   */
  protected static final String MIN_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMinValue() <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinValue()
   * @generated
   * @ordered
   */
  protected String minValue = MIN_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxValue() <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxValue()
   * @generated
   * @ordered
   */
  protected static final String MAX_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMaxValue() <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxValue()
   * @generated
   * @ordered
   */
  protected String maxValue = MAX_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #isCycle() <em>Cycle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCycle()
   * @generated
   * @ordered
   */
  protected static final boolean CYCLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCycle() <em>Cycle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCycle()
   * @generated
   * @ordered
   */
  protected boolean cycle = CYCLE_EDEFAULT;

  /**
   * The default value of the '{@link #getCache() <em>Cache</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCache()
   * @generated
   * @ordered
   */
  protected static final String CACHE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCache() <em>Cache</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCache()
   * @generated
   * @ordered
   */
  protected String cache = CACHE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SequenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.SEQUENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStartWith()
  {
    return startWith;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStartWith(String newStartWith)
  {
    String oldStartWith = startWith;
    startWith = newStartWith;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__START_WITH, oldStartWith, startWith));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIncrementBy()
  {
    return incrementBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIncrementBy(String newIncrementBy)
  {
    String oldIncrementBy = incrementBy;
    incrementBy = newIncrementBy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__INCREMENT_BY, oldIncrementBy, incrementBy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMinValue()
  {
    return minValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMinValue(String newMinValue)
  {
    String oldMinValue = minValue;
    minValue = newMinValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__MIN_VALUE, oldMinValue, minValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMaxValue()
  {
    return maxValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxValue(String newMaxValue)
  {
    String oldMaxValue = maxValue;
    maxValue = newMaxValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__MAX_VALUE, oldMaxValue, maxValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCycle()
  {
    return cycle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCycle(boolean newCycle)
  {
    boolean oldCycle = cycle;
    cycle = newCycle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__CYCLE, oldCycle, cycle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCache()
  {
    return cache;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCache(String newCache)
  {
    String oldCache = cache;
    cache = newCache;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SEQUENCE__CACHE, oldCache, cache));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.SEQUENCE__NAME:
        return getName();
      case MetaDslPackage.SEQUENCE__START_WITH:
        return getStartWith();
      case MetaDslPackage.SEQUENCE__INCREMENT_BY:
        return getIncrementBy();
      case MetaDslPackage.SEQUENCE__MIN_VALUE:
        return getMinValue();
      case MetaDslPackage.SEQUENCE__MAX_VALUE:
        return getMaxValue();
      case MetaDslPackage.SEQUENCE__CYCLE:
        return isCycle();
      case MetaDslPackage.SEQUENCE__CACHE:
        return getCache();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.SEQUENCE__NAME:
        setName((String)newValue);
        return;
      case MetaDslPackage.SEQUENCE__START_WITH:
        setStartWith((String)newValue);
        return;
      case MetaDslPackage.SEQUENCE__INCREMENT_BY:
        setIncrementBy((String)newValue);
        return;
      case MetaDslPackage.SEQUENCE__MIN_VALUE:
        setMinValue((String)newValue);
        return;
      case MetaDslPackage.SEQUENCE__MAX_VALUE:
        setMaxValue((String)newValue);
        return;
      case MetaDslPackage.SEQUENCE__CYCLE:
        setCycle((Boolean)newValue);
        return;
      case MetaDslPackage.SEQUENCE__CACHE:
        setCache((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.SEQUENCE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MetaDslPackage.SEQUENCE__START_WITH:
        setStartWith(START_WITH_EDEFAULT);
        return;
      case MetaDslPackage.SEQUENCE__INCREMENT_BY:
        setIncrementBy(INCREMENT_BY_EDEFAULT);
        return;
      case MetaDslPackage.SEQUENCE__MIN_VALUE:
        setMinValue(MIN_VALUE_EDEFAULT);
        return;
      case MetaDslPackage.SEQUENCE__MAX_VALUE:
        setMaxValue(MAX_VALUE_EDEFAULT);
        return;
      case MetaDslPackage.SEQUENCE__CYCLE:
        setCycle(CYCLE_EDEFAULT);
        return;
      case MetaDslPackage.SEQUENCE__CACHE:
        setCache(CACHE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.SEQUENCE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MetaDslPackage.SEQUENCE__START_WITH:
        return START_WITH_EDEFAULT == null ? startWith != null : !START_WITH_EDEFAULT.equals(startWith);
      case MetaDslPackage.SEQUENCE__INCREMENT_BY:
        return INCREMENT_BY_EDEFAULT == null ? incrementBy != null : !INCREMENT_BY_EDEFAULT.equals(incrementBy);
      case MetaDslPackage.SEQUENCE__MIN_VALUE:
        return MIN_VALUE_EDEFAULT == null ? minValue != null : !MIN_VALUE_EDEFAULT.equals(minValue);
      case MetaDslPackage.SEQUENCE__MAX_VALUE:
        return MAX_VALUE_EDEFAULT == null ? maxValue != null : !MAX_VALUE_EDEFAULT.equals(maxValue);
      case MetaDslPackage.SEQUENCE__CYCLE:
        return cycle != CYCLE_EDEFAULT;
      case MetaDslPackage.SEQUENCE__CACHE:
        return CACHE_EDEFAULT == null ? cache != null : !CACHE_EDEFAULT.equals(cache);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", startWith: ");
    result.append(startWith);
    result.append(", incrementBy: ");
    result.append(incrementBy);
    result.append(", minValue: ");
    result.append(minValue);
    result.append(", maxValue: ");
    result.append(maxValue);
    result.append(", cycle: ");
    result.append(cycle);
    result.append(", cache: ");
    result.append(cache);
    result.append(')');
    return result.toString();
  }

} //SequenceImpl
