/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.ShortCode;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Short Code</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.ShortCodeImpl#getShortCodeValue <em>Short Code Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ShortCodeImpl extends MinimalEObjectImpl.Container implements ShortCode
{
  /**
   * The default value of the '{@link #getShortCodeValue() <em>Short Code Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortCodeValue()
   * @generated
   * @ordered
   */
  protected static final String SHORT_CODE_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShortCodeValue() <em>Short Code Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortCodeValue()
   * @generated
   * @ordered
   */
  protected String shortCodeValue = SHORT_CODE_VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShortCodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.SHORT_CODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getShortCodeValue()
  {
    return shortCodeValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShortCodeValue(String newShortCodeValue)
  {
    String oldShortCodeValue = shortCodeValue;
    shortCodeValue = newShortCodeValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SHORT_CODE__SHORT_CODE_VALUE, oldShortCodeValue, shortCodeValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.SHORT_CODE__SHORT_CODE_VALUE:
        return getShortCodeValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.SHORT_CODE__SHORT_CODE_VALUE:
        setShortCodeValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.SHORT_CODE__SHORT_CODE_VALUE:
        setShortCodeValue(SHORT_CODE_VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.SHORT_CODE__SHORT_CODE_VALUE:
        return SHORT_CODE_VALUE_EDEFAULT == null ? shortCodeValue != null : !SHORT_CODE_VALUE_EDEFAULT.equals(shortCodeValue);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (shortCodeValue: ");
    result.append(shortCodeValue);
    result.append(')');
    return result.toString();
  }

} //ShortCodeImpl
