/**
 * generated by Xtext 2.21.0
 */
package com.jsantos.metadata.plugin.metaDsl.impl;

import com.jsantos.metadata.plugin.metaDsl.MetaDslPackage;
import com.jsantos.metadata.plugin.metaDsl.SqlNative;
import com.jsantos.metadata.plugin.metaDsl.SqlNativeBlock;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sql Native</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SqlNativeImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SqlNativeImpl#getSqlPosition <em>Sql Position</em>}</li>
 *   <li>{@link com.jsantos.metadata.plugin.metaDsl.impl.SqlNativeImpl#getSqlNativeBlocks <em>Sql Native Blocks</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SqlNativeImpl extends MinimalEObjectImpl.Container implements SqlNative
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSqlPosition() <em>Sql Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSqlPosition()
   * @generated
   * @ordered
   */
  protected static final String SQL_POSITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSqlPosition() <em>Sql Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSqlPosition()
   * @generated
   * @ordered
   */
  protected String sqlPosition = SQL_POSITION_EDEFAULT;

  /**
   * The cached value of the '{@link #getSqlNativeBlocks() <em>Sql Native Blocks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSqlNativeBlocks()
   * @generated
   * @ordered
   */
  protected EList<SqlNativeBlock> sqlNativeBlocks;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SqlNativeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaDslPackage.Literals.SQL_NATIVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SQL_NATIVE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSqlPosition()
  {
    return sqlPosition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSqlPosition(String newSqlPosition)
  {
    String oldSqlPosition = sqlPosition;
    sqlPosition = newSqlPosition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaDslPackage.SQL_NATIVE__SQL_POSITION, oldSqlPosition, sqlPosition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SqlNativeBlock> getSqlNativeBlocks()
  {
    if (sqlNativeBlocks == null)
    {
      sqlNativeBlocks = new EObjectContainmentEList<SqlNativeBlock>(SqlNativeBlock.class, this, MetaDslPackage.SQL_NATIVE__SQL_NATIVE_BLOCKS);
    }
    return sqlNativeBlocks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaDslPackage.SQL_NATIVE__SQL_NATIVE_BLOCKS:
        return ((InternalEList<?>)getSqlNativeBlocks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaDslPackage.SQL_NATIVE__NAME:
        return getName();
      case MetaDslPackage.SQL_NATIVE__SQL_POSITION:
        return getSqlPosition();
      case MetaDslPackage.SQL_NATIVE__SQL_NATIVE_BLOCKS:
        return getSqlNativeBlocks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaDslPackage.SQL_NATIVE__NAME:
        setName((String)newValue);
        return;
      case MetaDslPackage.SQL_NATIVE__SQL_POSITION:
        setSqlPosition((String)newValue);
        return;
      case MetaDslPackage.SQL_NATIVE__SQL_NATIVE_BLOCKS:
        getSqlNativeBlocks().clear();
        getSqlNativeBlocks().addAll((Collection<? extends SqlNativeBlock>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.SQL_NATIVE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MetaDslPackage.SQL_NATIVE__SQL_POSITION:
        setSqlPosition(SQL_POSITION_EDEFAULT);
        return;
      case MetaDslPackage.SQL_NATIVE__SQL_NATIVE_BLOCKS:
        getSqlNativeBlocks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaDslPackage.SQL_NATIVE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MetaDslPackage.SQL_NATIVE__SQL_POSITION:
        return SQL_POSITION_EDEFAULT == null ? sqlPosition != null : !SQL_POSITION_EDEFAULT.equals(sqlPosition);
      case MetaDslPackage.SQL_NATIVE__SQL_NATIVE_BLOCKS:
        return sqlNativeBlocks != null && !sqlNativeBlocks.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", sqlPosition: ");
    result.append(sqlPosition);
    result.append(')');
    return result.toString();
  }

} //SqlNativeImpl
